### ISSUE TITLE
Build static binary that can run on any Linux distribution

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1008]
@elsirion was able to build a binary for us using the following steps:

```
* open nix develop shell
* unset ROCKSDB_LIB_DIR so we statically link rocksdb
* rebuild from scratch with cargo clean and cargo build --release --bin ln_gateway
* copy binary over to ubuntu machine
* patchelf --set-interpreter /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 ln_gateway to set the dynmic linker to something available on the system
* (optional) remove rpaths with patchelf --set-rpath "" ln_gateway
```

We should figure out a way to do something like this via Nix.

**Comment by elsirion** [comment]
This could probably be done inside a nix derivation, there's good support for `patchelf`, typically just used the other way around. For the binary to be truly portable we'd need to link against `libmusl` afaik, otherwise we depend on having compatible `libc`s installed on target machines.

**Comment by justinmoon** [comment]
We discussed the need for this in discord today. Assigning to our nix wizard @dpc.

**Comment by dpc** [comment]
I've spent hours yesterday trying to get a musl build of fedimimd to work, always hitting some roadblock. The biggest offender seems to rocksdb, as it's a c++ code and it needs to link with musl-compat libstdc++ (or libc++, or something). Trying to compile with any already in binary cache fails due to various incompatibilities, while compiling for musl one of the existing packages takes forever (~1h on my system to compile llvm/gcc c++ stdlib) and fail during building or linking anyway. :/

It's also unclear if it will work even if c++ stdlib issue is solved. There are allegedly other issues with it: https://github.com/rust-lang/rust/issues/81987

**Comment by dpc** [comment]
It seems to me docker container might be our best best, at least for now.

**Comment by justinmoon** [comment]
from dev call: libc isn't meant to be statically linked, hence musl

**Comment by justinmoon** [comment]
from dev call: see what libc would be required to cover up-to-date debian / ubuntu and link against that as a half-measure ...

**Comment by dpc** [comment]
Given the rocksdb+C++ problems, I don't think I'm going to complete this. The Dockerfile will have to do for now.

**Comment by justinmoon** [comment]
Note that the biggest pain point here is the CLN plugin because that needs to be executed as a normal file (e.g. can't run independently in docker). But currently it requires RocksDB which can't be compiled with MUSL which would give us a static binary that runs on any Linux (poor C++ support). One option would be to have a gateway build that uses SQLite which may be easier to compile static binary. Another thing to mention is that the new lightning gateway architecture introduced in https://github.com/fedimint/fedimint/pull/1295 will remove `mint-client` dependency from CLN plugin so making a static binary for that will be easier.

**Comment by dpc** [comment]
I think this was largely addressed by https://github.com/fedimint/fedimint/pull/2036
