### ISSUE TITLE
Fix serialization for threshold_crypto public keys

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#109]
Our JSON files currently serialize `threshold_crypto::PublicKey` as an array of bytes and serialize `threshold_crypto::PublicKey` as an array of arrays of bytes. It would be better to use hex instead of arrays of bytes to serialize these public keys.

`#[serde(with = serde_binary_human_readable)]` seems to correctly hex-serialize `threshold_crypto::PublicKey`. But I'm not sure how to serizlize `threshold_crypto::PublicKeySet`. It doesn't have a way to iterate over the public keys because the `commit` attribute is private.

**Comment by chadat23** [comment]
I don't know if this counts as progress or being helpful but, in a toy example, I'm able to iterate over the `threshold_crypto::PublicKeyShare`s in a `threshold_crypto::PublicKeySet`, and a PublicKeyShare is a struct that wraps a PublicKey and implements `serde::Serialize` so I'm assuming I'm close to a solution.

I however haven't been able to use `#[serde(with = "serde_binary_human_readable")]` to serialize to hex since I keep getting errors when I try to use it (I'm pretty new to parts of this).

**Comment by justinmoon** [comment]
@elsirion: any pointers here?

**Comment by chadat23** [comment]
After some more tinkering I edited `serde_binary_human_readable::serialize` so that it iterates over PublicKeyShares in PublicKeySets. Now when I pass the toy struct:

`
struct Keys{
    #[serde(with = "serde_binary_human_readable")]
    pk: PublicKey,
    #[serde(with = "serde_binary_human_readable")]
    pks: PublicKeySet
}
`

into `serde_json::to_string`, I get:

`"\"pk\":\"86b3fef884829dc28345933cfcfd475a6291d8c3c8b0e51b7f14a2982a8712eecc9051e282c3d702d4cffd0968deb21f\",\"pks\":\"97d1e617f0645111e61d42f518640ef7e017582f90712d4d61a7a239624d7213375129f50ac0ace95c5a53c05fda6d1092268a01e86f1f7d0c1bdf61cada1b2f53c9e4335dacb32ede3a7dba86fbc6ae5df65aca55eb2061e44333c053fe56daa870b4e2cdfc68f970026092b107cce1ac9c229fc88aa1186836dcc3c75e70acf51a1b12d22637666616911cb8599b9e\"}"`

So it still needs some work, and I don't know the best way to add the extra formatting/info so as to not make it unnecessarily brittle, but I'm optimistic that this counts as progress.

**Comment by elsirion** [comment]
I don't understand the problem really, it seems to me that the LN module config is simply missing the `#[serde(with = serde_binary_human_readable)]` annotation and that's the problem? 

Looking at it from a higher level, `serde_binary_human_readable` is merely a hack we'd ideally get rid of because it uses `bincode` internally. The right thing to do™ would be to introduce a different serialization format in case of human readable serialization formats upstream like e.g. `bitcoin_hashes` does. That might even be easily possible since we already have a fork of `threshold_crypto`.

**Comment by chadat23** [comment]
At this point I have `serde_binary_human_readable` giving human readable keys for `SecretKey`, `SecretKeyShare`, `PublicKey` and `PublicKeySet` in my toy example when a struct with them is passed into `serde_json::to_string`. Does it make sense to use it as a stop-gap solution?

That said, I could obviously ignore this and redirect my efforts towards `threshold_crypto` if that makes more sense (I'm blindly assuming that that's comparably self contained).

**Comment by elsirion** [comment]
`serde_binary_human_readable` also implements deserialization (see the module). I'd just go with it for now.

**Comment by chadat23** [comment]
My approach for serializing doesn't play nice with the current deserialzation method for `PublicKeySet`. If it makes more sense, I'll take a look at changing serialization in `threshold_crypto`.

**Comment by NicolaLS** [comment]
completed by #393
