### ISSUE TITLE
fedimintd/src/distributedgen.rs shouldn't panic

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1211]
Perhaps it was OK when it was only a CLI, but now that it's a module that is also consumed by the admin UI we should be returning `Result`s.

**Comment by jkitman** [comment]
Here's a thought on handling fed setup:
- Before DKG starts wait for an 'ack' from all servers, we could send this ack as an async event to the UI to display which peers are ready
- Run DKG, return an error message rather than panic if something goes wrong (this shouldn't happen so long as all peers are honest)
- After DKG, send another 'ack' with a hash of the consensus config to verify we all have the same config (if not, warn the user that there are differences)
