### ISSUE TITLE
Gateway support for receiving multi-path payments

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1241]
If an incoming payment arrives split up across multiple HTLCs, we should be able to combine them (or whatever) and not just fail like we do currently.

**Comment by justinmoon** [comment]
One possibility is for for the gateway to attempt to combine HTLCs that are associated with a federation, but where there isn't a preimage for sale associated with it. [Here's an example](https://github.com/lightningd/plugins/blob/master/paytest/paytest.py) of a CLN plugin doing that.

Another option would be to get subscriptions from the lightning nodes (in Discord Rust Russell offered to create a `payment_accepted` hook) that we could subscribe to.

MPP and AMP are 2 different ways of doing multi-path payments. What are the relevant differences for us?

**Comment by m1sterc001guy** [comment]
Given that with the Lightning NG implementation, the gateway will be generating the invoice, I thought it would be a good opportunity to investigate if this can be leveraged to support MPP payments.

> MPP and AMP are 2 different ways of doing multi-path payments. What are the relevant differences for us?

My understanding is that AMP is essentially a series of keysend payments, where the receiver must have the [preimages from all of the payments to complete the payment](https://nullcount.com/what-is-the-difference-between-mpp-and-amp-payment-splitting/). Since Fedimint doesn't support keysend, I don't think we will be able to support this.

MPP does not use keysend and is not atomic, but essentially relies on the economic incentive that the receiver will not reveal the preimage until they have received all of the HTLCs for the payment (otherwise a node along the path could steal part of the payment).

For Fedimint, if we now have the assumption that the gateway generates the invoice, I am thinking we could potentially use HOLD invoices. For LND, we can use the `AddHoldInvoice` RPC to [register an invoice](https://lightning.engineering/api-docs/api/lnd/invoices/add-hold-invoice), [then subscribe to updates](https://lightning.engineering/api-docs/api/lnd/invoices/subscribe-single-invoice) for it using `SubscribeSingleInvoice`.  ([According to this document](https://lightningwiki.net/index.php/HODL_Invoice), `SubscribeInvoices` will not work, it needs to be the single invoice RPC). If the invoice status is updated to `ACCEPTED` only after all HTLCs are received for the payment, we could use this to support MPP payments. Currently, I'm not sure when the invoice's status is updated to `ACCEPTED`.

For core lightning, the path of supporting MPP is less clear to me. I think we will need that `payment_accepted` hook @justinmoon described above, or implement the logic ourselves using the `htlc_accepted` hook. For either of those, it doesn't appear that having core lightning generate the invoice gives us any benefit, but I could be wrong.

**Comment by elsirion** [comment]
LNv2 makes this irrelevant since payments terminate on the gateway's LN node.

**Comment by m1sterc001guy** [comment]
> LNv2 makes this irrelevant since payments terminate on the gateway's LN node.

I think there is actually still a todo here, during invoice generation we should turn on MPP payments. Ideally we'd also add a test too.

**Comment by elsirion** [comment]
Shouldn't the LN nodes the gateways uses do that by default by now?

**Comment by m1sterc001guy** [comment]
Will double check LND and LDK. I know for CLN our plugin would have needed some small changes (to handle HTLCs lower than the invoice amount), so perhaps once https://github.com/fedimint/fedimint/pull/6414 is merged there won't be anything to do for this.

**Comment by m1sterc001guy** [comment]
Confirmed LND and LDK support MPP
