### ISSUE TITLE
Consensus DB commits can panic

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1316]
We just experienced a panic in a live deployment on this line:

https://github.com/fedimint/fedimint/blob/73d851fc208f4bb0dadd65c148800a9c753a30d7/fedimint-server/src/consensus/mod.rs#L320

```
Jan 12 23:20:14 charlie fedimintd[32185]: 2023-01-12T23:20:14.174355Z  INFO fedimint_server:
Jan 12 23:20:14 charlie fedimintd[32185]: - Epoch: 510 [PeerId(0), PeerId(1), PeerId(2)] -
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 0: Transaction
Jan 12 23:20:14 charlie fedimintd[32185]:     Input: Lightning Contract f3dd1a942454997378c29814088d167470a45811ac636457a2f0ccd4ebf63730 with amount 40000000 msat
Jan 12 23:20:14 charlie fedimintd[32185]:     Output: Mint Coins 40000000 msat
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 0: Module CI: module=0 ci=Wallet Block Height 771650
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 0: Outcome Signature
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 1: Module CI: module=0 ci=Wallet Block Height 771650
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 1: Outcome Signature
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 2: Module CI: module=0 ci=Wallet Block Height 771650
Jan 12 23:20:14 charlie fedimintd[32185]:   Peer 2: Outcome Signature
Jan 12 23:20:14 charlie fedimintd[32185]: thread 'main' panicked at 'DB Error: Resource busy: ', /build/source/fedimint-server/src/consensus/mod.rs:302:36
Jan 12 23:20:14 charlie fedimintd[32185]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It is unclear to me why this error happened, there should not be any conflicting, parallel writes. That's why we need to review each call of `commit()` in the server code base and replace it with a loop that will re-try the transaction (re-creating it) so that this can not happen anymore. The consensus code should not have any side-effects not captured by the DB tx, so this seems safe (although inefficient, but it only seems to happen rarely).

**Comment by m1sterc001guy** [comment]
The documentation of commit() for a OptimisticTransaction in rocksdb states that commit can fail for two reasons:

1) It detected a write-write conflict (i.e two threads modified the same key/value at the same time)
2) If the memtable history size is not large enough, rocksdb will not be able to determine if a write-write conflict occurred, so it cannot safety commit.

As @elsirion mentioned above, there shouldn't be conflicting writes so it seems more likely to me that under a lot of load, the memtable history ran out of memory. This value can be adjusted but I doubt it can be changed dynamically at runtime (looks like its part of the Options struct that is passed to the db at creation time).

So in addition to refactoring the server commits so that they retry, I might also try to write a test to simulate a panic by setting this value very low.

**Comment by dpc** [comment]
> As @elsirion mentioned above, there shouldn't be conflicting writes so it seems more likely to me that under a lot of load, the memtable history ran out of memory. 

Very, very unlikely, I'd say. The workloads we're playing with right now are tiny.

**Comment by elsirion** [comment]
I think it's a write-write conflict with tx submission. Discussed with @jkitman today, we'll probably migrate away from the DB for that.
