### ISSUE TITLE
Don't attach e-cash outputs to LN offer creation transactions

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1319]
```
Jan 13 19:37:15 alpha fedimintd[42194]:   Peer 2: Transaction
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: LN offer for 1000 msat with hash be7b2e8660b5ca7975ebe1805060ee67f2df28237ca402f39a2b1553273d3c7a
Jan 13 19:37:15 alpha fedimintd[42194]:     Output: Mint Coins 0 msat
```

**Comment by justinmoon** [comment]
As context for @okjodom, transaction containing offer output gets created in `Client<UserClientConfig>.generate_invoice()`. That function only adds the offer output, so the extra 0 ecash output is added somewhere in the `self.submit_tx_with_change()` call. If you investigate that call stack, outputs get added in `MintClient.finalize_change()` so that must be the culprit.

Ended up implementing simple fix in https://github.com/fedimint/fedimint/pull/1328. But wanted to explain here so Jodom knows a little better how this works.

**Comment by dpc** [comment]
Should we use `NonZero<T>` for all thighs output amount to reject on type system level? @elsirion

**Comment by elsirion** [comment]
> Should we use `NonZero<T>` for all thighs output amount to reject on type system level? @elsirion

@dpc it would require something like `NonEmptyTieredMulti`. I don't think it's worth the hassle. Afaik `NonZero` mostly makes sense to save a byte for `Option`s etc.

**Comment by dpc** [comment]
Oh, right. Do we reject outputs with no amounts and tiers with no elements? Should we? Empty tiers break determinism of the encoding. I'm afk, will check later.

**Comment by dpc** [comment]
We should canonicalize at encoding and reject non canonical at decoding, it seems to be. Iirc we don't.

**Comment by justinmoon** [comment]
I wonder if server should reject zero-amount outputs, too?

**Comment by dpc** [comment]
On one hand it is allowed in L1 and useful there, on the other seems prone to abuse as we don't have any cost associated with it. But then people can just send find back and forth if they want some way to abuse things.
