### ISSUE TITLE
Stop using private __reexports module.

### ISSUE THREAD

**Issue by maan2003** [fedimint/fedimint#1346]
```
fedimint-bitcoind/src/bitcoincore_rpc.rs
5:use fedimint_api::module::__reexports::serde_json::Value;

modules/fedimint-wallet/src/lib.rs
32:use fedimint_api::module::__reexports::serde_json;

modules/fedimint-mint/src/config.rs
10:use fedimint_api::module::__reexports::serde_json;

modules/fedimint-mint/src/lib.rs
20:use fedimint_api::module::__reexports::serde_json;

modules/fedimint-wallet/src/config.rs
10:use fedimint_api::module::__reexports::serde_json;

modules/fedimint-dummy/src/config.rs
6:use fedimint_api::module::__reexports::serde_json;

modules/fedimint-dummy/src/lib.rs
16:use fedimint_api::module::__reexports::serde_json;
```
https://github.com/fedimint/fedimint/search?q=__reexports

**Comment by dpc** [comment]
`serde`, `serde_json` two main ones I can think of.

**Comment by elsirion** [comment]
This happens due to auto-imports imo. I agree with @dpc that we should just make them official (or otherwise remove them imo).

**Comment by dpc** [comment]
I don't think removing is even an option. If the user goes with their own import (which we currently do) and for whatever reason the cargo dependency resolver fails to unify their version, then the user code will stop compiling and get confusing error "expected serde_json::Value, got serde_json::Value`. IIRC the compiler got smarter in last few years and will hint the user that the versions might be not the same, but it's still odd, especially that the code might have been compiling a moment ago, and stopped because the user added some external dependency to their module code.
