### ISSUE TITLE
Move `hbbft` dependency from `fedimint-api` to `fedimint-server`

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1356]
We need to minimize dependencies on `fedimint-api` as everything is using it.

**Comment by thessc1** [comment]
Seems like a good first issue. Happy to tackle this one and #295. Any other comments?

**Comment by justinmoon** [comment]
It's all yours @thessc1!

**Comment by thessc1** [comment]
Is the ideal state for each module to not have any dependencies on the others? I can do a review to see if there are any others along with hbbft.

**Comment by elsirion** [comment]
> Is the ideal state for each module to not have any dependencies on the others?

It's a bit more nuanced. We did have some extended discussions a while ago from which this ideal structure emerged: https://github.com/fedimint/fedimint/blob/master/docs/modular-architecture.md

It's probably not a good task for someone new to the project since making the right decisions requires a lot of (sometimes historical) context.

What would be easier and also desired is looking into 3rd party dependencies that are only depended on by one or two crates (you can use `cargo tree` and `cargo tree -i package`) and figuring out if they can be removed by turning of unnecessary default features of dependencies.

**Comment by thessc1** [comment]
Alright, I'll stick to the 3rd party dependencies + hbbft for this one. Thanks!

**Comment by thessc1** [comment]
Question here, are we trying to remove nested dependencies, e.g. bitcoin is an explicit dependency, but also nested in lightning and miniscript? So, in this case would we want to turn off the defaults for lightning and miniscript and just use the explicit dependency?

Or alternatively, there's a dependency within most of these dependencies called proc-macro2. Do we want to remove that nested dependency and either make it explicit or only leave it within 1 dependency?

**Comment by dpc** [comment]
@thessc1 We should re-export the most common 3rd party crates that are part of the `fedimint-api`, and use these re-exports in downstream crates (everything else). `bitcoin`, `secp256k1`, `serde_json` - anything that is `pub` in `fedimint-api`.

**Comment by thessc1** [comment]
Just for clarification, we want to re-export the most commonly used 3rd party ones, e.g. maybe used in 3+ places. Anything else that is needed, but only used in a few places, we leave nested. And then anything that is part of a default, but isn't used at all, we just eliminate?

**Comment by dpc** [comment]
I think we can sort out the details of minor deps later. But the major ones that are used all over the public apis, yes.

**Comment by thessc1** [comment]
Cool, I'll pull out the major one's then.

**Comment by dpc** [comment]
BTW. There's this ugly `__reexports` there already, we should  probably reexport directly at the top level instead.

**Comment by elsirion** [comment]
HBBFT is gone, long live AlephBFT!
