### ISSUE TITLE
CI currently isn't running shell scripts

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#1379]
@dpc Not sure what went wrong, but seems for at least a week our GH actions aren't running the shell script based tests.  You can verify this by looking at the logs or modifying the scripts to fail.

**Comment by dpc** [comment]
Thanks for spotting it! I've got a fix.

**Comment by jkitman** [comment]
Now we are uncovering the silent errors :smile: 

`WIRE_UNKNOWN_NEXT_PEER` error is one I've been seeing in the cli-tests, maybe @okjodom can help fix?

**Comment by dpc** [comment]
He's on it. Pinged him on Discord.

**Comment by justinmoon** [comment]
This happens in tmuxinator when you create an invoice with `fedimint-cli` and pay it with `ln2`. 

![image](https://user-images.githubusercontent.com/4335621/213028032-884b0a60-4b10-41de-8cff-ea29f1ad8649.png)

This hack fixes it

![image](https://user-images.githubusercontent.com/4335621/213028351-3222a59a-4151-4649-9c9c-82ebd55baa09.png)

It seems that the `htlc_accepted` message we get from CLN changed. I experienced this in another deployment and was baffled because I didn't think I had updated CLN.

Did Nix update our CLN recently? I wonder if our change to short channel id's caused CLN to give us HTLCs in a different format?

**Comment by okjodom** [comment]
@justinmoon we last bumped to `cln-plugin` last month: See #1049 

If it's the case that [v0.1.1](https://crates.io/crates/cln-plugin/0.1.1) already included the breaking changes to `htlc_accepted`, then we'd need to redefine `HtlcAccepted` struct to this:

```
// TODO: Keep in sync with cln-plugin:
// See: https://github.com/ElementsProject/lightning/blob/master/doc/PLUGINS.md#htlc_accepted
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Htlc {
    pub short_channel_id: u64,
    #[serde(deserialize_with = "as_fedimint_amount")]
    pub amount_msat: Amount,
    pub cltv_expiry: u32,
    pub cltv_expiry_relative: u32,
    pub payment_hash: bitcoin_hashes::sha256::Hash,
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Onion {
    pub payload: String,
    pub short_channel_id: u64,
    #[serde(deserialize_with = "as_fedimint_amount")]
    pub forward_msat: Amount,
    pub outgoing_cltv_value: u32,
    pub shared_secret: bitcoin_hashes::sha256::Hash,
    pub next_onion: String,
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct HtlcAccepted {
    pub htlc: Htlc,
    pub onion: Onion,
}
```
