### ISSUE TITLE
Run fedimintd in replit

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1435]
This would be useful for getting development quickly, pair programming, conference workshops, and maybe even some deployments where people are just testing it out.

Progress started https://github.com/fedimint/fedimint/pull/556.

At the time we could run `cargo check` but not `cargo build` due to running out of storage space. [Replit CEO said scalable storage coming in January 2023](https://twitter.com/amasad/status/1602747313318875136?s=20).

**Comment by Kodylow** [comment]
could we publish fedimintd and the cli tools to the nix package registry? Replit runs a 10TB cache of nix registry packages to quickly load them into repls, that's why you can start bitcoind / cargo in seconds on a new repl. Doing the actual dev environment requires the increased storage for source files over the limits, but if we did a test release as a nix pkg you can load it into flask/react/next repls to actually use fedimint for demos.

**Comment by elsirion** [comment]
We can't publish until we actually do releases imo. Then it will be a question of what the nixpks repo's requirements are for inclusion.

**Comment by dpc** [comment]
From what I can tell nixpkgs is open for including legitimate packages in nixpkgs. Once we have stable releases, I'm quite sure they will be happy to accept a PR.

**Comment by justinmoon** [comment]
@Kodylow This one done now?

**Comment by Kodylow** [comment]
Getting the developer environment working yes, publishing as a nixpkg no

**Comment by justinmoon** [comment]
OK then let's close this as completed, and track the nix package in https://github.com/fedimint/fedimint/issues/3170
