### ISSUE TITLE
Test out SQLite in WASM

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1487]
https://github.com/fedimint/fedimint/issues/841#issuecomment-1399784665

**Comment by justinmoon** [comment]
Some discussions in sqlx repo:
* https://github.com/launchbadge/sqlx/search?q=wasm&type=issues
* https://github.com/launchbadge/sqlx/search?q=wasm&type=discussions

[Gist](https://gist.github.com/justinmoon/cc6d1af4ec86a7be3012681fedf7f722) attempting to compile `fedimint-sqlite` in WASM. Seems to only really complain about [mio](https://github.com/tokio-rs/mio).

**Comment by elsirion** [comment]
I took a quick glance and to my understanding they just have a suboptimal way of activating features for our use case which makes it hard to deactivate the networking/TLS dependency when it's not needed (i.e. when only SQLite is active, otherwise it's always needed afaik). If someone took a few days to fully understand their architecture it could probably be fixed though. The good thing with SQLite is we can probably just deactivate all the non-WASM-compatible parts since its requirements are minimal.

The next step would be to understand how WASM storage interacts with SQLite. Do we need to impl anything from the rust side (virtual file system access, …) or will it just work out of the box if compiled to WASM? 

The discussions in sqlx do not indicate any work on WASM, it's mostly people complaining about it not working as far as I can tell and one closed PR that was more interested in postgres+web sockets but got closed. What was the reason again for not going with rusqlite @m1sterc001guy? It might not be worth our time/aligned with sqlx's roadmap to allow SQLite-only WASM support.

**Comment by m1sterc001guy** [comment]
Main reason for not using rusqlite was that it didn't have async/await support.

Is there a wasm compatible function to run a function on another thread similar to `tokio::block_in_place`? I don't have much wasm experience but I seem to remember `spawn_local` being an option. If that works then I'm good with refactoring it to use rusqlite instead.

**Comment by elsirion** [comment]
`spawn_local` with blocking ops/`block_in_place` would be quite bad for a single-threaded executor, which seems to be the only option rn given how immature multi-threading support seems on WASM (didn't test, just read docs)?

@Maan2003 is working on an `IndexedDB` implementation, which seems like the better option for our use case. We might want to close this issue for now?

**Comment by Maan2003** [comment]
sqlite uses emscripten toolchain for wasm, which is [not compatible](https://github.com/rustwasm/wasm-bindgen/pull/2209) with `wasm-bindgen`

**Comment by m1sterc001guy** [comment]
Saw this on hackernews: https://blog.kebab-ca.se/chapters/2023-02-12-sqlite-wasm/overview.html

**Comment by justinmoon** [comment]
@m1sterc001guy Closing this since we removed sqlite
