### ISSUE TITLE
Global DB entries need a instance prefix in the DB

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1669]
Afaik there could be collisions between instance id prefixes and global fedimint DB keys right now. Global entries should use an isolated DB with the global instance id already uses by the DKG.

**Comment by m1sterc001guy** [comment]
We can do this. I don't think using an isolated db is the right solution though. The database transactions in `fedimint_server` are atomic over the global keys and the modules. So if you isolate a module dbtx from an already isolated database, it would end up nesting the module's prefix inside of the global prefix, which defeats the purpose of prepending the global prefix since it will be in front of all data.

I think `fedimint_server` needs to use separate `IsolatedDatabaseTransactions` whenever it is accessing the global keys vs the modules.

**Comment by dpc** [comment]
> So if you isolate a module dbtx from an already isolated database, it would end up nesting the module's prefix inside of the global prefix,

Yeah. It gets bit tricky.

IMO it is better to just allocate higher-values for prefixes for non-module stuff, and enforce that modules can only use `prefix < 192` or something like that.

**Comment by dpc** [comment]
We need a decent chunk of ids for global stuff, just in case we want some extra indexes etc. in the future, but 64 probably is enough, and we can always just use `0xff another_byte` if we really, really need to. Though 128 for modules is probably enough as well.

**Comment by m1sterc001guy** [comment]
Actually, is this a problem? We already prefix all module data with a prefix that indicates its a module (`MODULE_GLOBAL_PREFIX = 0xFF`)

The only keys that touch the database without prepending the `MODULE_GLOBAL_PREFIX` are defined in this enum:

```
#[repr(u8)]
#[derive(Clone, EnumIter, Debug)]
pub enum DbKeyPrefix {
    AcceptedTransaction = 0x02,
    DropPeer = 0x03,
    RejectedTransaction = 0x04,
    EpochHistory = 0x05,
    LastEpoch = 0x06,
    ClientConfigSignature = 0x07,
    Module = MODULE_GLOBAL_PREFIX,
}
```

So global data (e.g `AcceptedTransaction`) looks like this on disk:
`<0x02><AcceptedTransactionBytes>`

And module data looks like this:
`<0xff><2 byte module prefix><ModuleKeyBytes>`

Since `Module` is defined as `MODULE_GLOBAL_PREFIX` in this enum, I don't think it can ever conflict (unless we have 255 global keys, in which case we can make `MODULE_GLOBAL_PREFIX` 2 bytes).

Am I misinterpreting the issue?

**Comment by elsirion** [comment]
> Actually, is this a problem? We already prefix all module data with a prefix that indicates its a module (`MODULE_GLOBAL_PREFIX = 0xFF`)

I was not aware of that actually, that solves the problem, sorry for the confusion. This will also help me with the new client though where I have a similar problem and went the DB isolation path so far.
