### ISSUE TITLE
Authenticated API endpoints

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#1841]
Some functionality should only be available to the guardian running `fedimintd`. The easiest way to achieve this is via some bearer token, i.e. a random password, that is sent per connection open *or* per request (tbd).

The question is how to generate this token and communicate it to the guardian's client. Below I include a possible flow that I came up with a while ago:

1. Guardian generates registration QR (in terminal/web/whatever)
1.1 fedimintd generates short term secret and saves it in the DB
1.2 fedimintd encodes the secret together with the other join info in the QR
2. Guardian App scans QR
2.1 The app already has its root secret generated in the background
2.2 It derives an authentication key from the root secret
2.3 The authentication key is sent to this guardian's fedimintd, the request is authenticated with the short term secret from the QR
2.4 fedimintd checks if the short term secret used in the request is in the DB and removes it
2.4.1 If successful the authentication key (=long term secret) is saved to the DB
2.4.2 A second request would fail since the short term secret was removed
3. Any authenticated API requests can now be authenticated with the authentication key (=long term secret)

Ideally this functionality would be handled by Fedimint such that the API endpoint implementation merely receives a boolean stating if the request was made by a guardian (alternative: API endpoints include a flag if they are public or private). That way modules could also implement private API endpoints.

**Comment by jkitman** [comment]
Since the setup/admin UI will probably be browser-based, guardians may be logging in on a computer without camera support.

We already require the user to create a strong password when starting `fedimintd` for encrypting configs.  A salted hash of this password can be used to authenticate when logging into the setup/admin UI (since the admin endpoint might be exposed on a public IP).

The client UI could store this hash temporarily during each admin session, requiring users to enter their password periodically to login.  I think this works better from a UX perspective.  Eventually we could support two-factor auth if we want greater security for the admin UI.

**Comment by elsirion** [comment]
Sounds good to me, but also means we should enforce strong passwords.

**Comment by jkitman** [comment]
Yep you can also drop or ban IPs that attempt with too many bad passwords if brute-forcing via the API is a concern.
