### ISSUE TITLE
Remove `expect` call from `gateway-cli`

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1867]
Lots of `expect` call [here](https://github.com/fedimint/fedimint/blob/master/gateway/cli/src/main.rs). If the command failed, print message to STDERR. But don't panic.

**Comment by elsirion** [comment]
`main` already returns a `Result`:

https://github.com/fedimint/fedimint/blob/e5178267b58f184797c0fea2b004b83b8a12adbb/gateway/cli/src/main.rs#L66-L67

What happens if it's `Err`? If it does the right thin, we can just replace `expect` with `?` everywhere. If not we might want a `main_inner` function and then do the logging in case of errors in `main`.

**Comment by okjodom** [comment]
Good first issue claimed offline by @nassersaazi . Please post any questions or progress updates in this thread

**Comment by justinmoon** [comment]
Closed by #1993
