### ISSUE TITLE
Some outdated gateway code in flake.nix

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1873]
This looks outdated to me https://github.com/fedimint/fedimint/blob/4764e113639bcc86fddaebbf37a65b06a4e08ba2/flake.nix#L933-L996. `ln_gateway` has been removed. I'm not sure if `ln-gateway-container-entrypoint.sh` every actually worked ...

**Comment by okjodom** [comment]
There's no outdated or stale code / build config, but it's confusing because of the now outdated naming.
PR #1885 proposes rename of `ln-gateway-pkgs` to `gateway-pkgs`.

I think we need to be more careful with refactor of the docker container. Do we have any one using the published container at the moment? Can we safely rename the published container asset?

**Comment by justinmoon** [comment]
call: we should probably delete these and just make a OCI container build in flake.nix for gatewayd (create issue for this)

**Comment by okjodom** [comment]
Ref #1891

**Comment by justinmoon** [comment]
thanks @okjodom
