### ISSUE TITLE
On a failed CI test, dump content of client and server db

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#1924]
Register bash trap that on EXIT with non-zero status code, uses `dbtool <db> list` to dump the content of the DB.

Add some easily grepable headers to make locating it in the output easier.

**Comment by amit-62** [comment]
Hello @dpc I want to work on this issue. Can you provide some resources to get started.

**Comment by justinmoon** [comment]
@amit-62 Run tmuxinator and try the dbdump tool. Try to dump the client and server databases. Once you know how to run the dbdump tool, add something like [this](https://github.com/fedimint/fedimint/blob/master/scripts/build.sh#L93) to the end of `scripts/cli-test.sh`. Run that test locally, and check that database is dumped. Then make it so that this only happens if there is an error in the test -- for example, you can trigger this by putting `exit 1` somewhere in the `scripts/cli-test.sh`.

**Comment by amit-62** [comment]
Hello @justinmoon I ran `nix develop` command it took almost 6000 mb. Have I missed some configuration.

**Comment by amit-62** [comment]
I have used `just tmuxinator` command to run tmuxinator, am i going right?
How can I run dbdump tool? Please help me to set up codebase.

**Comment by dpc** [comment]
After the codebase was built it will be in `./target/debug/dbtool` or something like that. Run it with `--help` more arguments.

**Comment by amit-62** [comment]
Hello @dpc, I have been busy with my exam so I could not complete this issue. I am really sorry for it.
I have few problem I could not kill my` tmux` session using `ctrl + b`, is there any other way around.
And where can I get password and dir to pass as args to `./target/debug/dbtool`.
I could also not able to scroll through terminal screen after running `just tmuxinator`.
Where should I add greapable header.
Thank you.

**Comment by justinmoon** [comment]
Before you call `dbdump`, just do like `echo "## DBDUMP"

Try opening up a "draft PR" with your progress so far and we can give you more direction.

**Comment by amit-62** [comment]
Hello @justinmoon, I have created PR #2172 please review and suggest changes.

**Comment by elsirion** [comment]
I thought we fixed this by uploading the whole test dir, but apparently it's broken.

![Screenshot 2024-01-16 at 17-25-31 Add backwards-compatible test matrix · fedimint_fedimint@9bc838d](https://github.com/fedimint/fedimint/assets/84478054/562c2259-7d1a-474c-bd89-671b1ac6481d)

**Comment by dpc** [comment]
@elsirion Link would be more useful. :P

**Comment by elsirion** [comment]
Good point, I initially wanted to just close this PR but then checked a random failed build and noticed there were no files. But turns out I got a very special failed build, an "out of disk space" one, but assumed this to be the general case. https://github.com/fedimint/fedimint/actions/runs/7549996146?pr=4010

I now checked a few others where uploading worked and think we can close this issue :tada:
