### ISSUE TITLE
Don't fork cln_plugin

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1978]
https://github.com/ElementsProject/lightning/pull/6041 was just merged into upstream

**Comment by elsirion** [comment]
Releases of the rust crates [seem to be independent of CLN itself](https://github.com/ElementsProject/lightning/issues/5988). I guess we can use CLN master for a while and when we want to release a version we'd have to lobby CLN to make a release.

**Comment by cbergqvist** [comment]
TODO: Possibly remove/hide the https://github.com/fedimint/lightning/ repo once people are on branches using #3101.

**Comment by elsirion** [comment]
I don't think we need to remove the fedimint fork of rust-lightning. It's not shown on the organization page and doesn't bother anyone.

**Comment by cbergqvist** [comment]
> Could you clarify what you mean exactly? I don't see any instances of `https://github.com/fedimint/lightning/ ` on master branch right now. This issue seems complete?

Since this issue is called "Don't fork cln_plugin", closing it might imply that the forked repo no longer exists. Sure, it is not referenced from the master branch any longer, I meant we might want to delay the removal for a while if people are working off un-rebased private branches for prolonged time.

> I don't think we need to remove the fedimint fork of rust-lightning. It's not shown on the organization page and doesn't bother anyone.

"lightning", the main C CLN repo contains the Rust CLN plugin crate in the `plugins`-subfolder and is still visible in the repositories list further down here: https://github.com/fedimint/
But I'm fine with this issue being closed too. 👍
