### ISSUE TITLE
Only use 1 core-lightning RPC crate

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#199]
Right now we use both of these:
- https://crates.io/crates/clightningrpc
- https://crates.io/crates/cln-rpc

**Comment by elsirion** [comment]
We need to collect what features cln-rpc is missing. Long term cln-rpc is the way to go imo because it has a higher chance of being maintained (as part of core-lightning). 

Changes we need:
- [ ] `connect` command (I think @jkitman ran into this problem)

Nice to have:
- [ ] various API improvements, see https://github.com/ElementsProject/lightning/pull/5258

Feel free to edit that list.

**Comment by jkitman** [comment]
At least one API command was missing and another failed because it was passing in a deprecated parameter.  Hard to say exactly what was missing until we try to remove the clightningrpc entirely.

**Comment by justinmoon** [comment]
We don't use `clightningrpc` anymore
