### ISSUE TITLE
Replace invalid chars in peer_name with '_'

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2074]
Right now, peer names with invalid TLS domain chars will cause failures.  It's a better user experience just to replace them with valid chars.

**Comment by justinmoon** [comment]
I remember trying a peer name of 3 before and that didn't work either, oddly. Maybe I'm mis-remembering.

**Comment by SumantxD** [comment]
I would like to work on this issue , after going through [https://github.com/fedimint/fedimint/pull/2068](url) i have made following observations ("correct me if i am wrong") :-

1) ConfigGenConnectionsRequest in /fedimint-core/src/admin_client.rs is used to send URL by admin user to the API 
2) before sending to the API we have to make sure that the URL is valid because right now invalid TLS domain chars is causing 
    failures

proposed solution:

-> To ensure that the Url in leader_api_url is always valid, you can use Rust's Url crate to parse the URL and return an error if 
    the parsing fails.
-> I can implement a function that takes a string as input and returns a Result<Url, String> type that either contains the parsed 
     Url (which has every invalid chars replaced with '_') or an error message if the parsing fails.

If i am not wrong then could you @jkitman assign me this issue, or suggest some changes in the proposed solution.
Thank You

**Comment by jkitman** [comment]
@SumantxD the best place to sanitize the string is where it is used as a TLS domain here https://github.com/fedimint/fedimint/blob/master/fedimint-server/src/net/connect.rs#L173
