### ISSUE TITLE
Docs explain what trusting fedimint's cachix during initial dev shell setup means

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2149]
It can speed up nix command builds. At least explain what that means since you'll be asked.

**Comment by AnmolSirola** [comment]
@dpc can I work on this issue.

**Comment by dpc** [comment]
Go for it!

**Comment by collins-okafor** [comment]
@dpc can I still work on this issue?

**Comment by dpc** [comment]
There's no need really to ask can you work on something. It's an Open Source project. You're free to work on anything you want, and PRs are always welcome as long as they match the goal of the project. Just try to pick something you have a good understanding how to do well, because time is limited so we don't have a lot of time to help newcomers with every detail. Submit a PR, get it merged, and you'll maybe get a :cookie: .
