### ISSUE TITLE
Rethink connection retry timeouts

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#2263]
See https://github.com/fedimint/fedimint/pull/2253#discussion_r1171833588

**Comment by douglaz** [comment]
> > The problem with the "production" delay is that due to its exponential nature it may lead to very high "tail latencies".
> 
> I don't understand this one.
> 
> Usually what I'd implement is exponential + ceiling (like 10/30/60s). So it does 1ms,2ms,4,8 and eventually just constant 10s.

My mistake here. It isn't currently exponential (which would make things only worse), but it still keeps increasing and there is a high ceiling, so eventually the test will take much longer than expected.

The ceiling is defined by https://github.com/fedimint/fedimint/blob/master/fedimint-server/src/net/peers.rs#L37 and enforced by https://github.com/fedimint/fedimint/blob/master/fedimint-server/src/net/peers.rs#L435

The maximum delay for a single reconnection on default/production settings right know is:
`4 * 300 seconds = 20 minutes`

Under the `TEST_DEFAULT` profile this was at most:
`4 * 300 * 0.1e-3 seconds = 120ms`

So it would keep a safe limit even under stress scenarios.

Perhaps we don't want <1s reconnection delays because this may trigger some warnings, but for a test you also don't want anything longer than that because a test is more of a "speedrun" than a "normal game".

I'll create a PR with one possible solution.

**Comment by dpc** [comment]
> The maximum delay for a single reconnection on default/production settings right know is:

20 minutes sounds like very much, even for production. Even 1s from peers is not going to cause any strain, 60s would be a reasonable value that would allow quick re-connection after host comes back online.

> Perhaps we don't want <1s reconnection delays because this may trigger some warnings, but for a test you also don't want anything longer than that because a test is more of a "speedrun" than a "normal game".

Ideally, sure. But if we have a bug and for some reason the test can't reconnect, then we get a flood of messages that are making debugging experience rather bad.

I think it would be better if the reconnection was initially fast, but after a decent enough time, slowed down significantly. Using exponents in around 1.1-1.6 might give such a result.

BTW. Would be great to see reconnection counters if we're not printing them already. At least it helps correlated these messages.

**Comment by douglaz** [comment]
> > The maximum delay for a single reconnection on default/production settings right know is:
> 
> 20 minutes sounds like very much, even for production. Even 1s from peers is not going to cause any strain, 60s would be a reasonable value that would allow quick re-connection after host comes back online.
> 
> > Perhaps we don't want <1s reconnection delays because this may trigger some warnings, but for a test you also don't want anything longer than that because a test is more of a "speedrun" than a "normal game".
> 
> Ideally, sure. But if we have a bug and for some reason the test can't reconnect, then we get a flood of messages that are making debugging experience rather bad.
> 
> I think it would be better if the reconnection was initially fast, but after a decent enough time, slowed down significantly. Using exponents in around 1.1-1.6 might give such a result.
> 
> BTW. Would be great to see reconnection counters if we're not printing them already. At least it helps correlated these messages.

Generally I agree, I've created https://github.com/fedimint/fedimint/pull/2267 without big changes but perhaps we can already try a exponential approach

**Comment by douglaz** [comment]
Exponential delay and clear floor/ceiling limits:
https://github.com/fedimint/fedimint/pull/2285
