### ISSUE TITLE
Initialize Setup UI project

### ISSUE THREAD

**Issue by isaack-njama** [fedimint/fedimint#2298]
Setup Typescript + Chakra project

**Comment by elsirion** [comment]
Please make sure it works in the nix environment and does not require system-wide dependencies so that non-UI devs can also make minor changes without spending a lot of time on setup. Me and @dpc can help with that if necessary.

**Comment by justinmoon** [comment]
Currently we have a nix shell for the gateway UI that can be used via:

```
nix develop .#gateway-ui
```

The only extra dependency it has is `yarn`: https://github.com/fedimint/fedimint/blob/55ed759d991ad30e189eee53423264da2930aa5f/flake.nix#L447-L450

I propose we just rename that shell to `ui` and this new UI can use that. I also propose we refer to the code for this UI as the "Guardian UI" since Guardians are who will use it. It will have 2 somewhat distinct sets of functionality for "setup" of new federation and "admin" of running federation. That make sense?

**Comment by isaack-njama** [comment]
> Currently we have a nix shell for the gateway UI that can be used via:
> 
> ```
> nix develop .#gateway-ui
> ```
> 
> Once you run ^^, you can run `yarn install` and `yarn start` to install Typescript dependencies and run the UI locally. The only extra dependency it has is `yarn`:
> 
> https://github.com/fedimint/fedimint/blob/55ed759d991ad30e189eee53423264da2930aa5f/flake.nix#L447-L450
> 
> I propose we just rename that shell to `ui` and this new UI can use this as well. I also propose we refer to the code for this UI as the "Guardian UI" since Guardians are who will use it. Sound good?

Sounds good @justinmoon. Cool if I make a PR to rename the `gateway-ui` shell to `ui`?

**Comment by isaack-njama** [comment]
> Please make sure it works in the nix environment and does not require system-wide dependencies so that non-UI devs can also make minor changes without spending a lot of time on setup. Me and @dpc can help with that if necessary.

Under which directory should the project be?

**Comment by justinmoon** [comment]
> Sounds good @justinmoon. Cool if I make a PR to rename the gateway-ui shell to ui?

Go for it! I would say call it `web`. Do it [here](https://github.com/fedimint/fedimint/blob/55ed759d991ad30e189eee53423264da2930aa5f/flake.nix#L447).
