### ISSUE TITLE
Writing to the DB in the API isn't always safe

### ISSUE THREAD

**Issue by jkitman** [fedimint/fedimint#2387]
We will get DB write errors if multiple clients cause writes to the same key.  We could either send all API events that want to write to the DB to consensus via a channel (probably best) or lock via a Mutex on DB writing API calls.

**Comment by m1sterc001guy** [comment]
> We could either send all API events that want to write to the DB to consensus via a channel (probably best) or lock via a Mutex on DB writing API calls.

I don't think we should do this, this would essentially be re-implementing MVCC at the application level. The database already takes care of concurrency. Both of these solutions just serialize access to the database which wouldn't be good for perf.

The write errors are occurring because it is not possible to safely concurrently modify the same key. Simply serializing the transactions breaks snapshot isolation though. An update could be lost (lost update anomaly) or the "wrong" value could be persisted.

IMO APIs that are sensitive to this issue should either 1) take a lock at the API layer but before accessing the db so that all requests to this endpoint are serialized or 2) Just return an error back to the client that indicates the client should retry.

**Comment by jkitman** [comment]
@m1sterc001guy good points!  We first hit this error when both the API and consensus were writing transactions (this is more serious since it can crash consensus, whereas we catch the API error).  Now we are hitting it again with the count of times the client's join code is used (API-only).

I'd like to find a trade-off between safety (not crashing consensus) and not adding unnecessary complexity.

**Comment by m1sterc001guy** [comment]
Agreed that API requests shouldn't crash consensus.

For the case of the join codes, it doesn't look like those are used in consensus right? In that case I think its fine to take a Mutex when the API is called (serialize all requests to this specific API) or just return an error and have the client retry.

There's probably not a simple solution for module developers, if they want their API to support multiple concurrent requests they'll need to think about concurrency. In my opinion its a good thing that the db returns the error, at least it prevents the database from becoming corrupted.

**Comment by jkitman** [comment]
Spoke with @elsirion, we think it could be dangerous for module devs to be able to write to the DB so we could give them read-only access in the APIs.  Our core API could still write to the DB since we can make sure to manage that safely ourselves.

We just need a way to share state between the APIs and consensus, giving them a [left_right](https://docs.rs/left-right/latest/left_right/) might make the most sense, since that way consensus isn't blocked from reading if the API is being spammed with writes.

**Comment by dpc** [comment]
This is a very old issue, and I don't think is a problem anymore. Please re-open if I'm missing something.
