### ISSUE TITLE
Client-NG: join federation

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#2506]

**Comment by justinmoon** [comment]
This only applies to the CLI, correct?

**Comment by justinmoon** [comment]
Call: this should retry if we encounter errors (e.g. write errors produced by download tokens)

**Comment by justinmoon** [comment]
Call: save client config to db, not filesystem

**Comment by okjodom** [comment]
> Call: save client config to db, not filesystem

@elsirion, would this be a the client rocks db, or a new one referenced by fedimint-cli?

If we were to use the db we pass to client runtime, should we then expect `ClientBuilder` to load the config from this DB instead of `ClientBuilder::with_config` convenience?

**Comment by justinmoon** [comment]
> @elsirion, would this be a the client rocks db, or a new one referenced by fedimint-cli?

I think it would be the same db the client uses for everything else

**Comment by okjodom** [comment]
[WIP](https://github.com/fedimint/fedimint/compare/master...okjodom:cfg-in-db?expand=1) that I'm yet to make a PR because I'm not sure how (or if we need to) get connect info to `ClientBuilder` and have `ClientBuilder::build` also persist the config to db. Perhaps have a `with_connect_info` convenience on the builder as an alternative to `with_config`?

This initial draft just migrates the `ClientConfig` persistence from file to db but within the same `JoinFederation` command of fedimint-cli
