### ISSUE TITLE
Internal fedimint transaction still requires the presense of a lightning gateway

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#2618]
While reviewing https://github.com/fedimint/fedimint/pull/2602 I noticed that we still use the lightning gateway's public key to determine if the payment is to another user within the federation by looking at the route hints in the lightning invoice. This works, but it implies that if a user just wants to do an internal transfer within the federation, there still needs to be a lightning gateway even though the gateway is not being used (https://github.com/fedimint/fedimint/pull/2602 refactors the internal logic to be in the client, rather than the gateway).

The main scenario that this would address would be a mint that does not have any lightning gateway connected, but still wants to produce invoices to users to do internal transfers.

Had some offline discussion with @okjodom and @justinmoon. One suggestion was to transform the federation id into an elliptic curve point, then put that in the route hint of the invoice. The client could then directly determine which federation the invoice belonged to, without needing a lightning gateway present.

**Comment by elsirion** [comment]
> One suggestion was to transform the federation id into an elliptic curve point, then put that in the route hint of the invoice.

That sounds like a great solution for the "no gateway connected" use case! The pay function could simply check if the route hint contains that special node pub key, if so it _definitely_ is an internal payment since the node doesn't exist, if not we can still check the route hint node against known gateways and if that fails it's an external payment.

**Comment by justinmoon** [comment]
> One suggestion was to transform the federation id into an elliptic curve point, then put that in the route hint of the invoice.

Where exactly would we put it? A single-hop route hint containing this pubkey?

**Comment by elsirion** [comment]
> An extra single-hop route hint containing this pubkey?

Not an extra one, since there wouldn't be any without a gateway being present and this proposal is only necessary in the "no gateway" case. So with this proposal there would be one route hint to a non-existing LN node.

> One option would be to use this federation id-derived pubkey as the node pubkey in the invoices

I thought about that, but we need to be able to sign using the key, so everyone would need to know the private key and who knows what assumptions that breaks …

**Comment by okjodom** [comment]
> > One option would be to use this federation id-derived pubkey as the node pubkey in the invoices
>
> I thought about that, but we need to be able to sign the invoice using the key, so everyone would need to know the private key and who knows what assumptions that breaks …

Probably not true. I think we only need the federation id derived pubkey as a replacement of `src_node_id` in the last route hint hop. Clients still get to create and use their temporary keypair they use as their own node secret key and node public key.

now taking a closer look at that part of the code to test the proposal
