### ISSUE TITLE
Run unittests, clippy and rustfmt CI workflows in Nix

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#265]
We tried doing this, but kept getting this error:

```
error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/ubuntu/actions-runner/_work/minimint/minimint/target/debug/deps/libproc_macro_error_attr-bc2c9c0f5c4cdebb.so)
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
error: could not compile `proc-macro-error` due to previous error
```

[This was a good link explaining what's happening](https://discourse.nixos.org/t/glibc-2-33-vs-2-34-rust-madness/18909).

We tried `nix-shell --pure`, removing `Swatinem/rust-cache@v1`, removing cachix, setting `LD_LIBRARY_PATH = "${pkgs.glibc.out}/lib";` in `shell.nix`. But kept getting the same error.

If you want to attempt, you can use [this commit](https://github.com/fedimint/minimint/commit/5d837563db894e77e5eac21dcd2d1399ed7f2d9e) as starting point.

**Comment by dpc** [comment]
This is a known problem when using impure Nix derivation (which includes `rustup`-provided `rustc` binary). Some macro evaluation during build want to link to a library path that is not there (was when `rustc`, or `libstd` or something was built outside of your current Nix derivation), or something like that.

IMO, you should really convert everything in flake-based setup, otherwise there are always papercuts and problems. BTW. [I just happened to discussion in `rust-bitcoin` something very relevant](https://github.com/rust-bitcoin/rust-bitcoin/discussions/1096#discussioncomment-3149258)

**Comment by elsirion** [comment]
The problem I have with flakes right now is that it's hard to get set up for devs. On NixOS I'd have to change my system configuration and on other systems idk. That means it would work for CI (where we can have a more involved setup) but doesn't seem suitable for a dev environment unless there's an easy fix we can put into a shell script.

**Comment by dpc** [comment]
> On NixOS I'd have to change my system configuration and on other systems idk

I was just setting it up on an Ubuntu and it was easy and fast.

I already converted my NixOs to use flake-based system configuration, but I don't think it's necessary just to enable flakes.

And also - it's **totally worth it**. OMG, I love flakes. Before flakes everything in Nix seemed always clumsy. After flakes everything fits neatly and I am able to setup up super neat things. `</coolpersonalstorybro>`

**Comment by elsirion** [comment]
Maybe we should give it a shot @wiredhikari :laughing: I'm slowly getting convinced ^^

**Comment by dpc** [comment]
https://github.com/rustshop/rustshop/blob/main/README.onboarding.md BTW.

**Comment by dpc** [comment]
Done.
