### ISSUE TITLE
Documentation for docker-based deployment of gatewayd and fedimintd

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2665]

**Comment by nassersaazi** [comment]
@justinmoon i could write this up. any hints on where to look? 👀

**Comment by nassersaazi** [comment]
i have successfully run the docker-compose in the ui repo and i have also looked at scripts/start-containers.sh in the fedimint repo, though here i got some problems with certs generation. 
 i have some questions:

- how different are these two in terms of functionality and containers run?
- is it the right approach to just transfer and document the docker-compose set up from the ui repo and put it into the fedimint repo or are there some additional steps required.
- am also curious about why fedimint opted for scripts instead of setting up a docker-compose directly as it's done in the UI repo?

**Comment by m1sterc001guy** [comment]
`scripts/start-containers.sh` is mostly legacy and was built when we only could do DKG from the cli rather than through the new UI. Now that the new UI is in place, it makes it much easier to create a single docker-compose file rather than use the functions in `scripts/start-containers.sh`.

Using the docker-compose file is the correct way to go and we should probably delete `scripts/start-containers.sh` now that that's in place.

**Comment by justinmoon** [comment]
This is done
