### ISSUE TITLE
Wallet client doesn't detect address re-use

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2749]
If you send twice to an address generated by the wallet client, the wallet client will only peg-in the first one

**Comment by elsirion** [comment]
We'd need to spec out the expected behavior:
* We **cannot** keep watching all addresses we ever generated, so there has to be some time limit (it can be generous)
* During that time limit we should process any peg-ins we detect
* With some effort we could implement a command that rescans a particular address or all addresses ever generated
* Another approach would be letting users designate certain addresses as "forever addresses" and accept the small performance hit for permanently watching a very limited set of addresses

**Comment by dpc** [comment]
This should be fixed via wallet client module refactor that was part of 0.4
