### ISSUE TITLE
Config API: `run_dkg` method returns immediately

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2781]
This would mean running DKG in the background and having the client polls the status.

**Comment by wbobeirne** [comment]
Just wanted to expand on this a bit since this came up again in discord. The problem is that `run_dkg` blocks its response until dkg has completed. For clients on bad networks, or if one of the clients goes offline (or closes a browser tab) in the middle of dkg, this request times out (code `-32001`). Future attempts to call `run_dkg` now fail with `Expected to be in SharingConfigGenParams state`, so our setup is completely bricked since we're stuck in this state, but dkg has stopped being attempted by our server.

Instead, the call to `run_dkg` should return as soon as the server is in a state of _attempting_ to run dkg, and we should just poll the status (or hey, use websocket events to let us know when statuses change!) While in this state, dkg should continuously be attempting to run rather than only trying to run while a `run_dkg` request is still hanging.
