### ISSUE TITLE
Configurable ports for servers and ln-gateway

### ISSUE THREAD

**Issue by NicolaLS** [fedimint/fedimint#304]
Right now we set the ports static for:
- servers in configgen: 
  - hbbft communtication 4000 + i (4000 for server 0 etc.)
  - api 5000 + i

- the ln-gateway always binds to 8080 
- (and clientd will always bind to 8081)

The ports could be given as arguments for the `server` and `ln-gateway` binaries

**Comment by elsirion** [comment]
With the distributed config generation change we'll have to set the hbbft port (also used for configgen) and API port (also used for configgen web UI) either as a command line option or as a environment variable since they'll be needed before there is any real config.

The other two should be configurable but idk how (config or cmd line option).

**Comment by NicolaLS** [comment]
> With the distributed config generation change we'll have to set the hbbft port (also used for configgen) and API port (also used for configgen web UI) either as a command line option or as a environment variable since they'll be needed before there is any real config.
> 
> The other two should be configurable but idk how (config or cmd line option).

So do you think it'd be good to approach this before the whole configgen changes or should I remove this issue and we do it in one go (all in the new configgen) ?

**Comment by jkitman** [comment]
We could do this as a separate change, leaving the ports fixed (based on `PeerId`) in the initial distributed config gen, allowing only the remote server addresses to be configurable.

However, I'd like to tackle this after the distributed config gen to minimize the conflicts since the logic may change considerably.

**Comment by justinmoon** [comment]
We should also make sure that all hostnames are configurable. For example, right now there's no way to bind the gateway to `0.0.0.0` currently without changing the code.

**Comment by justinmoon** [comment]
I think these are all done, right?

`distributedgen` allows us to configure hostname and ports for p2p and public api.

`gateway-cli generate-config` allows us to do so for gateway.
