### ISSUE TITLE
just mprocs does not work on macOS

### ISSUE THREAD

**Issue by joschisan** [fedimint/fedimint#3136]
guardian processes just show this error:

tail: cannot open '/tmp/nix-shell.6RUytq/nix-shell.obbI8b/fm-OUoW/logs/fedimintd-0.log' for reading: No such file or directory

**Comment by a-moreira** [comment]
@joschisan I have been able to run `just mprocs` on a macOS M1 yesterday with no problems.
How did you install Nix? Did you follow the instructions [here](https://github.com/fedimint/fedimint/blob/master/docs/dev-env.md)? What version of macOS are you using? Is it Apple Silicon or Intel?

**Comment by dpc** [comment]
> tail: cannot open '/tmp/nix-shell.6RUytq/nix-shell.obbI8b/fm-OUoW/logs/fedimintd-0.log' for reading: No such file or directory

This might be expected. Possibly devimint did not start `fedimintd` yet. Check what `devimint` tab is showing.

**Comment by joschisan** [comment]
> > tail: cannot open '/tmp/nix-shell.6RUytq/nix-shell.obbI8b/fm-OUoW/logs/fedimintd-0.log' for reading: No such file or directory
> 
> This might be expected. Possibly devimint did not start `fedimintd` yet. Check what `devimint` tab is showing.

2023-09-12T12:13:17.526238Z  INFO devimint: Test setup in "/tmp/nix-shell.6RUytq/nix-shell.obbI8b/nix-shell.ymmLPM/fm-iF8U/cfg"
2023-09-12T12:13:17.528868Z  WARN devimint::external: Failed to create wallet ... retrying JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 61) LOG_DEVIMINT="devimint"
2023-09-12T12:13:38.445280Z  INFO devimint::util: sending SIGKILL to bitcoind and waiting for it to exit LOG_DEVIMINT="devimint"
2023-09-12T12:13:38.462070Z  WARN devimint: Main process failed with JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 35), will shutdown
Error: JSON-RPC error: transport error: Couldn't connect to host: Resource temporarily unavailable (os error 35)

**Comment by dpc** [comment]
> `2023-09-12T12:13:38.445280Z INFO devimint::util: sending SIGKILL to bitcoind and waiting for it to exit LOG_DEVIMINT="devimint"`


This doesn't look good. Is there a chance you have a regtest bitcoind already running?

**Comment by joschisan** [comment]
> This doesn't look good. Is there a chance you have a regtest bitcoind already running?

If so only if it could have been started in an earlier test of my pr and somehow was not killed. Never started anything explicitly.

**Comment by justinmoon** [comment]
I was just debugging this with @joschisan a bit. I also have an m2 mac and I tried `just mprocs` on exactly the same commit today and had no issues. It doesn't seem like the issue is some daemon continuing to run in the background because he restarted his computer and had same issue. I don't think he's running `bitcoind` or `lnd` or anything else like that outside of fedimint dev environment. 

It seems like devimint is trying to do `json-rpc` with bitcoind, that fails because bitcoind hasn't started up, and devimint just exits. But not sure because `2023-09-12T12:13:17.528868Z WARN devimint::external: Failed to create wallet ... retrying JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 61) LOG_DEVIMINT="devimint"` log doesn't contain enough context to know exactly what is trying to do json-rpc. Another thing that's weird is that the next line in the logs says it's sending `SIGKILL` to `bitcoind`, but `bitc oind` continues to run in his mprocs UI.

**Comment by dpc** [comment]
Try in `nix develop --ignore-environment` shell BTW.

**Comment by dpc** [comment]
@joschisan Did it ever got resolved?

**Comment by joschisan** [comment]
> @joschisan Did it ever got resolved?

@justinmoon wanted to look into it

**Comment by justinmoon** [comment]
I couldn't replicate. Don't understand what's wrong.

**Comment by dpc** [comment]
Can you capture the `$FM_DATA_DIR`, tar it and send it to me?

**Comment by justinmoon** [comment]
@joschisan Did we resolve this?

**Comment by joschisan** [comment]
> @joschisan Did we resolve this?

no

**Comment by dpc** [comment]
> Can you capture the `$FM_DATA_DIR`, tar it and send it to me?

:point_up: @joschisan

**Comment by justinmoon** [comment]
@joschisan told me this works now
