### ISSUE TITLE
Support re-attempting LN invoice payment

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#3248]
Currently the Lightning client module declines to pay the same LN invoice twice since this is the easiest way to make sure that we do not lose money. The problem with this is that temporary failures (e.g. receiver offline) cannot be solved by trying to pay the same invoice again.

To enable safe multi-payment attempts we need to check:
* That in case of previous failures the contract is fully refunded before we fund it again (otherwise we might pay a multiple of the invoice amount to the gateway)
* That if the payment succeeded previously we just return the preimage without funding the contract again

The gateway would likely also need to be adjusted such that it doesn't forever return the same result for the same invoice (it probably does so rn to ensure idempotency of its API).

How to achieve this is an open question. We could add an index to the contract, i.e. if the contract with index 0 failed we fund one with index 1. If hashed into the contract ID we'd automatically get a new contract and a lot of idempotency problems go away because each contract still only gets used once. At the same time the client complexity, especially for backup/recovery, increases.

**Comment by m1sterc001guy** [comment]
I elected only to use the index in the `OperationId` and not the `Contract` so that it is easy to verify that no other contracts are being created concurrently (since they have the same `contract_id`), but we still can disambiguate between payment attempts. I think this works but let me know if I'm missing something that requires the index to be on the `contract`.
