### ISSUE TITLE
Can't backport PRs because docs links to files on master branch that have been deleted

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3277]
https://github.com/fedimint/fedimint/pull/3274#issuecomment-1730386775

**Comment by dpc** [comment]
BTW. Markdown links are not a required check, so they shouldn't be blocking anything. @justinmoon 

>    Can markdown do relative links?

In our case there's no such thing, as how the markdown files get rendered and where shown (under what URL) is decoupled from the markdown files itself.

Because of this we use absolute URLs instead.

I think it's not the end of the world that links stopped working on a (soon to be) "old" release branch.

But generally I'd advise not linking to the code from docs and move code documentation into the code.

**Comment by justinmoon** [comment]
> so they shouldn't be blocking anything.

TIL 👍 

Yea I guess it's fine if markdown links just stop working on the release branch. At least at this stage. Will close for now and anyone who feels strongly the other way can re-open (and fix :))
