### ISSUE TITLE
Investigate rust native DB alternatives

### ISSUE THREAD

**Issue by shaurya947** [fedimint/fedimint#3398]
https://surrealdb.com/docs/introduction/concepts in embedded mode or something else perhaps? Not sure what the state of the art landscape looks like.. 

@m1sterc001guy in case you have any insights

**Comment by elsirion** [comment]
We had some traumatizing experiences with sled in the early days 😅 feel free to play around with other DBs but we'll probably stick with RocksDB for a while since we got it to work quite nicely now.

**Comment by m1sterc001guy** [comment]
I did some initial investigations that I wrote up here: https://github.com/fedimint/fedimint/discussions/1836

SurrealDB certainly looks interesting, it was not my on radar. The challenge with supporting different databases is the differing semantics between implementations, sometimes there's slight variations in concurrency/execution patterns. We had Sqlite support in Fedimint for awhile, but found it difficult to maintain due to the differing concurrency semantics. SurrealDB even looks like it has a different data model which makes it even more challenging.

For Fedimint, the main features we rely on are Optimistic Transactions and snapshot isolation with concurrent writers. If there's another embedded DB that supports all of those, we probably could get it to work. I would agree with Eric though that the effort required to do that is probably too great right now.

**Comment by tvolk131** [comment]
@shaurya947 would you want to move the discussion on SurrealDB over to #1836 and close this issue?

**Comment by justinmoon** [comment]
> @shaurya947 would you want to move the discussion on SurrealDB over to #1836 and close this issue?

Let's do this to keep discussion in 1 place. Linked to this issue from https://github.com/fedimint/fedimint/discussions/1836 so we don't lose the content.
