### ISSUE TITLE
Add a lot of debug logging to the gateway

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3477]
Today @douglaz, @okjodom and I were trying to debug an issue with the gateway and we noticed that logging is very insufficient. This is understandable because we completely re-wrote the gateway losing some useful logging that accumulated in the old gateway, and we haven't run it in production much yet.

**Comment by m1sterc001guy** [comment]
Any suggestions on what to add? We don't currently log on successful payments iirc, we should probably add that.

This is probably a good first issue.

**Comment by douglaz** [comment]
I would consider some things:
- Track of payments, both success and failure with easy to read logs. Today we have some debug statements that shows part of the state machine where we can search for a given amount for instance, but it's very hard to read. It would be good to be able to grep the whole process of the payment since the beginning until its success/failure. Perhaps we should attach some temporary id to every logging statement
- Related to above, perhaps we could have some pretty print of state machines in general
- If there is a loop, we must know if the loop is stuck or not (more important for loop {...} statements than for ... in ...)
- If it makes a I/O or RPC call, we must know if it is attempting to make that call and if it failed or not. Also we should consider adding timeouts here to detect and proper log "blocking" or slow calls

All note that the logging shouldn't be excessively verbose (i.e it must be compatible with DEBUG level, we can't rely on TRACE level for production purposes)
