### ISSUE TITLE
Gateway fails to run state machines until it's restarted

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3478]
We are running a federation with `v0.1.3` release. It is in a region with pretty poor internet connectivity in general. Everything was working smoothly for a few days. Then all-of-a-sudden lightning payments started to fail. If you generated an invoice using `fedimint-cli`, and called `fedimint-cli wait-invoice` it would get to the `WaitingForPayment` state and get stuck there.

From the gateway logs ([which are pretty sparse](https://github.com/fedimint/fedimint/issues/3477)) it seemed like the gateway's `handle_htlc_stream` was seeing the HTLC, and [this database commit](https://github.com/fedimint/fedimint/blob/master/fedimint-client/src/lib.rs#L632-L639) was being hit.

But the gateway's fedimint transaction buying the preimage from the federation was never being confirmed by the federation. In fact, it seemed like the `submit_transaction` RPC method wasn't getting called because [this log](https://github.com/fedimint/fedimint/blob/4943c209c1ba02f8e5b92d2db7f636373fe24b48/fedimint-server/src/net/api.rs#L209) wasn't showing up. But if we restarted the gateway, both that log and the transaction itself would show up. The `fedimint-cli wait-invoice...` command which was previously stuck on `WaitingForPayment` also promptly completed.

We thought the root cause was jsonrpsee slots getting exhausted so we tried https://github.com/fedimint/fedimint/pull/3471 and https://github.com/fedimint/fedimint/pull/3470 but neither worked.

We decided to spin this gateway down and setup another to get things working again. In the process of withdrawing funds, the `withdrawal` command from `gateway-cli` also failed to complete until the gateway was restarted which suggests the problem is somewhere in the state machine executor.

**Comment by justinmoon** [comment]
Call: we need better tooling to inspect state machines when debugging things like this

**Comment by douglaz** [comment]
One of the problems is due to payment taking too long. Currently we have this:
```rust
impl GatewayPayInvoice {
    fn transitions(
        &self,
        global_context: DynGlobalClientContext,
        context: GatewayClientContext,
        common: GatewayPayCommon,
    ) -> Vec<StateTransition<GatewayPayStateMachine>> {
        vec![StateTransition::new(
            Self::await_get_payment_parameters(global_context, self.contract_id, context.clone()),
            move |_dbtx, result, _old_state| {
                Box::pin(Self::transition_buy_preimage(
                    context.clone(),
                    result,
                    common.clone(),
                ))
            },
        )]
    }
```
On `transition_buy_preimage` we will send a
```rust
client
                .router()
                .send_payment_v2(SendPaymentRequest {
                    payment_request: invoice.clone(),
                    allow_self_payment: true,
                    no_inflight_updates: false,
                    timeout_seconds: LND_PAYMENT_TIMEOUT_SECONDS,
                    fee_limit_msat,
                    ..Default::default()
                })
```

But what if we are paying a [HODL Invoice](https://voltage.cloud/blog/lightning-network-faq/understanding-hold-invoices-on-the-lightning-network/)?

It won't timeout because the payment is InFlight, it won't also fail. So it will wait for it to settle for minutes, hours, days...

But note that we are waiting inside a STATE TRANSITION, which is global for all state machines. So everything else on the gateway will freeze/not progress.

So the solution is probably to move this InFlight payments to a specific state. @m1sterc001guy thoughts?

**Comment by m1sterc001guy** [comment]
Ah yes, nice catch. This is a problem. I think we perhaps forgot to move this back into the trigger function once we made our LN `pay` implementations idempotent. Either way, the fix should be to move this function into the trigger function.

I actually don't think we want a new state. I think we want to combine this with `await_payment_parameters` (and give that function a new name) since we should validate the payment parameters before attempting to pay.

I think almost all of `transition_buy_preimage` can be moved into the trigger function (or split into multiple trigger functions). The transition function should essentially just validate the result and return the new state.
