### ISSUE TITLE
Add validate command to `mint-client-cli`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#362]
Currently we can only claim e-cash tokens with the CLI client. For debugging having the ability to simply validate tokens without claiming them would be useful.

**Comment by wilfredallyn** [comment]
This looks like a good first issue to try as I'm learning Rust. Can you assign it to me?

**Comment by wilfredallyn** [comment]
I am working on finding the logic for validating tokens so that I can copy it in cli code.

I found a coin validity check in the [`create_input_from_coins`](https://github.com/fedimint/fedimint/blob/138851e2cede68e2a2a2a5dd858d6b43680513dc/client/client-lib/src/transaction.rs#L49-L70) function in the `TransactionBuilder`. Is this the logic I should replicate?

I also found that coins are verified in the [`build_verification_cache`](https://github.com/fedimint/fedimint/blob/c08c10cb9c0c52f07255a7bf35b0db3fb340e2a9/modules/minimint-mint/src/lib.rs#L139-L160) function. Should I be using this logic instead?

**Comment by justinmoon** [comment]
A coin is 2 things: nonce and a signature from the federation. For a coin to be "valid", 2 conditions must be met: 

1. The signature must be a valid signature from the federation public key associated with coins of that denomination. This is checked by the federation in `Mint::build_verification_cache()`.
2. The nonce must be unspent. After every redemption of a coin the nonce of that coin is saved in the database as "spent". This is how we achieve double-spend protection. This is checked by the federation in `Mint::validate_input`.

This issue is about making this check from the client side, not the server side. It is pretty straightforward to check the signature because the relevant public keys are in `ClientConfig.mint.tbs_pks`. The hard part is knowing whether the nonce is spent or not. I'm not sure how we should do this. Perhaps we need a new federation API for this? Thoughts @elsirion?

**Comment by elsirion** [comment]
My idea was only checking the validity of the signature.

https://github.com/fedimint/fedimint/blob/ecba28a085ebfad7d9537e95d0b5a9c5ea3e9db1/modules/minimint-mint/src/lib.rs#L627-L631

**Comment by justinmoon** [comment]
Ahh ok. Let's just go with that for now. Someday when we add a public "spent nonce" API we can upgrade this to also check if the nonce is spent.

**Comment by elsirion** [comment]
Yep, I'd like to make `client-cli` a versatile and composable tool over time that we can use for all kinds of debugging and testing. Having the functionality separate is good imo.

**Comment by justinmoon** [comment]
I think this was closed by #456
