### ISSUE TITLE
`audit` RPC logs logs "DatabaseTransaction has writes and has not called commit" warning

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3750]
Run `just mprocs` and then `fedimint-cli  --our-id 0 --password pass admin audit` and you'll see `WARN db: DatabaseTransaction has writes and has not called commit.` in the `fedimint0` tab. @bradleystachurski could you look into this?

While investigating this I noticed that we don't really have good coverage of non-module RPC calls like this. `audit` has no test coverage at all as far as I can tell. There also isn't really an easy place to add such test coverage. Perhaps we need a `fedimint-server-tests` crate? Writing a devimint test is kind of a lot of work -- especially when you can't figure out how to pass `auth` correctly in the shell! 

On the other hand, a test wouldn't have caught this because it's just a warning. Perhaps this specific warning should be a hard failure in the context of our integration tests?

Perhaps this issue relates to the increase in audit duration if we're failing to commit some of the compaction?

**Comment by bradleystachurski** [comment]
Thanks for flagging!

Looks like we refactored `process_consensus_item` in fedimint-mint-server so the compaction for keys is now happening in the `audit` method, which takes a non-committable dbtx when invoked from the audit endpoint.

https://github.com/fedimint/fedimint/pull/3419/commits/2b9e256c1d20dae5269db0cf84a8edf298d5093e#diff-76ea3178abbb4b0250345ce75a0104a96850a1da23577c3a2d45a43bac4c607fL445-L452

https://github.com/fedimint/fedimint/pull/3419/commits/2b9e256c1d20dae5269db0cf84a8edf298d5093e#diff-76ea3178abbb4b0250345ce75a0104a96850a1da23577c3a2d45a43bac4c607fR413-R420

(GH defaults to collapsing the above links, so you may need to expand `modules/fedimint-mint-server/src/lib.rs`)

I think it makes sense to use a non-committable dbtx when we're constructing an audit from the endpoint, since we don't want to mutate state to run an audit from an external request. `process_consensus_item` in the consensus server will construct an audit and commit the results of compaction, which seems like an appropriate interval to compact mint audit keys. 

https://github.com/fedimint/fedimint/blob/c4e41f0490ff6e6c245f5ba1bb30a5f98d5a3a68/fedimint-server/src/consensus/server.rs#L619

**Comment by bradleystachurski** [comment]
@justinmoon The associated PR only addresses the WARN logs. Perhaps we should create a separate issue/discussion to tackle the other points you brought up?

**Comment by justinmoon** [comment]
> @justinmoon The associated PR only addresses the WARN logs. Perhaps we should create a separate issue/discussion to tackle the other points you brought up?

I don't think this is actionable yet. Was kind of just thinking out loud.
