### ISSUE TITLE
fedimint-cli can't withdraw "all"

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#3752]
From `just mprocs`:

```
$  fedimint-cli withdraw --amount all --address bcrt1quluutn45cmz76sqy85ahmrx3lzpfzqe2yq2yja
2023-11-28T04:18:49.629733Z  INFO fedimint_cli::db_locked: Acquiring database lock
2023-11-28T04:18:49.810847Z  INFO fedimint_client::sm::executor: Starting state machine executor task
2023-11-28T04:18:49.829455Z  INFO fedimint_client: Last client reference dropped, shutting down client task group
2023-11-28T04:18:49.829508Z  INFO fedimint_client::sm::executor: Shutting down state machine executor runner due to shutdown signal
{
  "error": "CliError",
  "kind": "general_failure",
  "message": "failure",
  "raw_error": "Federation didn't return peg-out fees"
}
```

Server logs:

```
WARN fedimint_wallet_server: Error returning peg-out fees Not enough SpendableUTXO
```

We really need to add tests before merging things like this going forward.

**Comment by elsirion** [comment]
That's an interesting one! What I think happens is that `GW balance == federation balance`. When the federation is asked for a fee estimate it internally tries to construct a tx that sends this amount, but fails because including the fee it's not possible.

What it likely should do is just assume that all UTXOs are spent completely and return the fee for that, then the client would subtract that fee from the total amount and withdraw the total federation balance, consuming all UTXOs, instead of failing.

Idk how probable this case is irl as some e-cash will always be lost.

**Comment by justinmoon** [comment]
@elsirion https://github.com/fedimint/fedimint/pull/3755 closes this as well. The CLI was multiplying instead of dividing when doing msat -> sat conversion 😬.
