### ISSUE TITLE
Database overwriting element when expecting insertion of new entry

### ISSUE THREAD

**Issue by douglaz** [fedimint/fedimint#3937]
Under high load on local devimint (`just mprocs`), using:
```
fedimint-load-test-tool --users 200 ln-circular-load-test --test-duration-secs 200 --strategy two-gateways
```
We got errors like this on three guardians:
```
WARN db: Database overwriting element when expecting insertion of new
            entry. Key: MintOutputOutcomeKey(OutPoint { txid: e93aec9348dffaefef1a2cce7a85c91639f5317e9722cd8d5acc0556071469a3, out_idx: 2 }) Prev Value: V0(MintOutputOutcomeV0(BlindedSignatureShare(G1Affine { x: 0x0fce9224e29f55294a9e42824c67fd9ef8f71b8202aac0b778534f380abbf4c226e79ea4fefa9d97faea209a8363be83, y: 0x15cfe04f49a6a3ae403f4472dcf2ffa3b7cbd5437af21068a250c6acba63d3dee883a4ea1e1935e1552824d6fec53a88, infinity: Choice(0) })))
```
Also this on one guardian:

```
WARN db: Database overwriting element when expecting insertion of new
            entry. Key: ProposeDecryptionShareKey(613552750709715775c7300d081de3f9519f269e5b7e09cb272ab1e9ece9daca) Prev Value: PreimageDecryptionShare(DecryptionShare(...))
```

**Comment by elsirion** [comment]
There is a race condition in `submit_transaction`: we check if the transaction was already accepted in on DBTX and if not run verification of the transaction in another DBTX. In the meantime the transaction can be processed by consensus and cause the verification to overwrite existing data. But since that verification DBXT is never committed this isn't a problem.

Fix: just use the same DBTX.

https://github.com/fedimint/fedimint/blob/9e602232396572add80ecfef2a8a14a56bdba0c6/fedimint-server/src/net/api.rs#L98-L132

**Comment by AnmolSirola** [comment]
@elsirion can I work on this issue :)

**Comment by douglaz** [comment]
> @elsirion can I work on this issue :)

Sure, just do it

**Comment by mubarak23** [comment]
> There is a race condition in `submit_transaction`: we check if the transaction was already accepted in on DBTX and if not run verification of the transaction in another DBTX. In the meantime the transaction can be processed by consensus and cause the verification to overwrite existing data. But since that verification DBXT is never committed this isn't a problem.
> 
> Fix: just use the same DBTX.
> 
> https://github.com/fedimint/fedimint/blob/9e602232396572add80ecfef2a8a14a56bdba0c6/fedimint-server/src/net/api.rs#L98-L132

@elsirion can you add more context to this, i will like to work on it

**Comment by elsirion** [comment]
The idea is to move the `let mut dbtx = self.db.begin_transaction_nc().await; ` line up and use that `dbtx` for the check if we already processed that transaction. End result: we start one database transaction instead of two in that fn, guaranteeing consistency/atomicity of our read and fixing the race condition that was reported.

**Comment by mubarak23** [comment]
> The idea is to move the `let mut dbtx = self.db.begin_transaction_nc().await; ` line up and use that `dbtx` for the check if we already processed that transaction. End result: we start one database transaction instead of two in that fn, guaranteeing consistency/atomicity of our read and fixing the race condition that was reported.

I get the idea what we are trying to do here,

kindly assign, i will submit a PR for this

**Comment by mubarak23** [comment]
@elsirion  this is has been worked on already and is available on master branch

**Comment by elsirion** [comment]
Thx! Must have forgotten to close/tag the PR.

**Comment by mubarak23** [comment]
> Thx! Must have forgotten to close/tag the PR.

i will look another issue

**Comment by elsirion** [comment]
Thank you for digging this one up and making us aware of it already being solved!
