### ISSUE TITLE
Look into `ClientSMDatabaseTransaction`

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4002]
This might have become redundant due to a recent refactor by @dpc. `ClientSMDatabaseTransaction` was introduced to limit a DBTX to the module's DB partition when owned by a module, but allow general DB access when owned by core code. I think to remember having seen something similar under a different name recently.

**Comment by m1sterc001guy** [comment]
I will also review this when I can

**Comment by m1sterc001guy** [comment]
Unless I'm missing something, with the refactored database structures I still don't see an easy way to convert a "prefixed" `DatabaseTransaction` back to a non-prefixed `DatabaseTransaction`, which I believe is what we need. The tricky part is that the module code needs access to the global database transaction (e.g for functions like `claim_input`, so we can't just pass the prefixed `DatabaseTransaction` from the executor to the state transition function.

Some other possible options:

1) Pass the module instance id into the state transition function. Breaks some of the abstraction but this is essentially what we're doing with `ClientSMDatabaseTransaction` anyway.
2) Add a `strip_prefix` or something to `DatabaseTransaction` to allow going from a prefixed transaction back to a global transaction.
3) Just refactor `ClientSMDatabaseTransaction` into `fedimint-core` and rename it so its not just a client-side abstraction. This struct could hold an (optional) prefix and have the ability to access either the global dbtx or the prefixed dbtx

**Comment by dpc** [comment]
> This might have become redundant due to a recent refactor by @dpc. ``

I've looked at it while doing the refactor and I don't think they are redundant. `ClientDbTxContext` is the new similar struct, and maybe they can be unified, but I kind of doubt it, because `ClientDbTxContext` has a wider "scope/meaning" and thus comes with bunch of extra operations (and possibly even more in the future).

> 1. Pass the module instance id into the state transition function.

Breaking abstraction doesn't seem worth it.

> 2. Add a strip_prefix or something to DatabaseTransaction to allow (..)

Breaks abstractions. We do not want the module to have any ability to get access to global db.

> 3. Just refactor ClientSMDatabaseTransaction into fedimint-core


The abstraction / isolation depends on `pub(crate) fn global_tx` which will break if we move it out of `fedimint-client`



Generally I don't see any problem with `ClientSMDatabaseTransaction` to justify any extreme changes. Maybe we could rename to `StateTransitionTransaction` or `StateTransitionContext` etc. to clarify and make the name less cryptic. Or merge it with `DynGlobalClientContext` or something.


If we wanted to get rid of t, then the way to do it would be to break the call chain to avoid needing it. The module state transition logic is potentially calling something like:

```
global_context.claim_input(dbtx, input).await.0
```

"to call-in into internal logic" which under the hood "unwraps the global dbtx out of `dbtx`.

I find it all quite reasonable, similiar to how `ClientContext` works and don't see any good way to get rid of the whole thing completely.
