### ISSUE TITLE
Add commando CLN gateway

### ISSUE THREAD

**Issue by jb55** [fedimint/fedimint#4034]
It would be nice if fedimint supported talking to CLN nodes without any additional software. CLN comes with commando baked in, which is an RPC mechanism over lightning packets.

I wrote lnsocket (commando lib) which has some very early rust support, so I may look into PRing this if interested. I am looking into running a fedimint node and this would be my ideal mode of operation since I only run my CLN node on an isolated machine and not much other software. Definitely not RTL.

**Comment by EthnTuttle** [comment]
What advantage does this form of communication have over the gateway plugin?
And talk to the fedimint in what way? The gateway acts as a client, providing LN sats for ecash

**Comment by jb55** [comment]
if the gateway plugin adds CLN rpcs, then commando would just be a way to call these RPCs over lightning instead of using gRPC or some rpc mechanism outside lightning + runes. It's a much simpler and secure way to do RPC on CLN.

I see that your libs fully assume gRPC so maybe this is a waste of time.

**Comment by m1sterc001guy** [comment]
> I see that your libs fully assume gRPC so maybe this is a waste of time.

Our LND implementation actually does something similar to what you're describing. The LND implementation just overrides our `ILnRpcClient` trait and doesn't use gRPC, so a similar thing should be possible with commando.

I don't have much experience with commando though, so main thing I'm wondering is if it supports HTLC interception? We use this currently for receiving into a fedimint, so that the mint has a chance to respond with the preimage. If that is supported, then this should be doable.

**Comment by elsirion** [comment]
The problem with the CLN integration is that we need HTLC interception and the "normal" RPC APIs don't expose that, only the plugin API does. So the official gRPC plugin doesn't expose it either (https://github.com/ElementsProject/lightning/issues/6508) and probably neither does commando. That's why we have to run our own plugin in CLN unless we want to support outgoing-only gateways, which is much less efficient though imo since it reduces automatic rebalancing.

**Comment by jb55** [comment]
yea I noticed that, which is why I closed the issue. didn't realize fedimint needed htlc interception. I will keep reading the code to try to figure out why.
