### ISSUE TITLE
set_active_gateway is not concurrency safe

### ISSUE THREAD

**Issue by Maan2003** [fedimint/fedimint#4110]
https://github.com/fedimint/fedimint/blob/11339763400401b5394e726b05bf6decc031283e/modules/fedimint-ln-client/src/lib.rs#L866-L888

if called concurrently, second one would panic on database commit

**Comment by Maan2003** [comment]
cc @dpc

**Comment by dpc** [comment]
The only reason I'm on the git blame there is because I shuffled this code around.

Though I recognize this code and was already SMH looking at it before. Smells like globals to me, so I don't like it.

The immediate solution would be to wrap it into autocommit. 

But possibly the whole thing could be scrapped and the caller could do it's job and track and pass the gateway it wants to use or something? Again - I'm not sure, I don't know that code very well.

**Comment by m1sterc001guy** [comment]
Yeah I don't think this code was ever designed with concurrency in mind. Long term I'd like to remove the concept of "active" gateway altogether and replace it with something smarter (like policies based on fees or reliability). 

Even wrapping in an autocommit is a bit weird, it essentially means that the first call to `set_active_gateway` is overwritten, which might not be expected. `commit_tx` here should probably be propagated up so that the caller can properly handle it.

**Comment by okjodom** [comment]
Seems today we only use this api in test cases where we to pre-activate a specific gateway before asserting some behavior

**Comment by elsirion** [comment]
On master we can already optionally specify the gateway for a payment, this should become the standard way of doing it, getting rid of the active gateway concept. Otherwise it's also impossible to show users a reliable fee preview for outgoing payments since the active GW may change in the meantime.

**Comment by justinmoon** [comment]
Some discussion about "active gateway" here https://github.com/fedimint/fedimint/issues/3844
