### ISSUE TITLE
Clarify error handling plan

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#416]
I see open PRs using `.expect` for error handling (like client network connectivity issues). I'd like to clarify what's the plan.

I highly recommend https://blog.burntsushi.net/unwrap/#what-does-it-mean-to-panic as good source of information on idiomatic error handling in Rust. I think I agree 100% with everything stated there.

> While panics can be used for error handling, it is generally regarded as a poor form of error handling. 

Sub-tasks:

* [ ] gather consensus around the matter,
* [ ] stop accepting new code using `expect`/`unwrap` for non-internal programming errors and gradually replace the existing usage, 
* [ ] consider using `eyre_color` instead `anyhow`, or even `error-stack` for application-error handling (no strong opinions there, but `eyre_color` seems to be gaining traction over `anyhow` and `error-stack` has a new, entirely different approach that is [very interesting as well](https://hash.dev/blog/announcing-error-stack) and is based on [future-looking plans for Error handling for Rust](https://rust-lang.github.io/rfcs/3192-dyno.html?)).

**Comment by elsirion** [comment]
Yep, imo there are two classes of code:
1. Things we want to get production ready that will interface with users in some form (`fedimintd`, `client-lib`, `ln_gateway`)
2. Things only (a) used internally or (b) not ready for prime time yet (`mint-client-cli`, `clientd`)

I think for 1 we definitely want to avoid panics for every possible error, so panics always indicate programmer errors. So `expect` would only be used where we are sure that it will never panic and document *why* in the expect message. `unwrap`s should never be used since they don't explain why it's ok to do.

An exception we'll have to grandfather in for a while is DB errors since they are `expect`ed all over the place and need a separate fix as discussed in #374.

We might also want to extend this approach to 2b (@NicolaLS). 2a isn't a priority imo.

**Comment by dpc** [comment]
Seems like we've did a lot of progress towards converting all expects to `?`, and we settled on combination of `anyhow` for erased errors and `thiserror` for places where we do want to list each single error case.

Closing as nothing distinctly actionable is to be done about it.
