### ISSUE TITLE
Devimint should save one invite code per guardian

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#4225]
Currently devimint just save 1 invite code for the whole federation. But since invite codes currently only encode a single guardian url, but commit to the others, this invite code isn't usable if the guardian who issued this invite code is offline. This was just causing a test with one guardian offline to randomly fail for me.

https://github.com/fedimint/fedimint/blob/7fe0a203af3bd9683d4f856baa9c517ec9bad2f6/devimint/src/federation.rs#L171-L179

**Comment by kernelkind** [comment]
Hi, this is my first issue so I'm going to describe my thought processes for how I plan on solving it.

It looks like this issue occurs because only one of the guardian's urls is saved in the invite code. Instead, all of the guardian's urls should be saved to the `InviteCode` struct. 

https://github.com/fedimint/fedimint/blob/06dcc978fa48d73ad61cbc48c6dafb42325149e7/fedimint-core/src/api.rs#L771C1-L776C6
should be modified to be:
```
new(api_endpoints: Vec<(PeerId, SafeUrl)>, federation_id: FederationId) -> Self
```
Then, each entry in `api_endpoints` can be saved as an `InviteCodeData::Api`.

 https://github.com/fedimint/fedimint/blob/06dcc978fa48d73ad61cbc48c6dafb42325149e7/fedimint-core/src/api.rs#L779C5-L779C33
 
becomes `InviteCode::urls(&self) -> Vec<SafeUrl>`

and

https://github.com/fedimint/fedimint/blob/06dcc978fa48d73ad61cbc48c6dafb42325149e7/fedimint-core/src/api.rs#L791C5-L791C33

becomes `InviteCode:peers(&self) -> Vec<PeerId>`

All of the usages of `InviteCode::new` would of course be modified to accommodate this new constructor, including
https://github.com/fedimint/fedimint/blob/06dcc978fa48d73ad61cbc48c6dafb42325149e7/fedimint-server/src/config/mod.rs#L262C1-L270C6

Instead of only including the current api endpoint, include all of them (all of the guardians). This method is used to write the invite code to the `invite-code` file.

Then, in `federation.rs`, since the invite code will contain the urls for all of the guardians, it's fine to just get the invite code from the first guardian since they will all contain the urls for all of the guardians.

**Comment by elsirion** [comment]
@kernelkind this would make the invite codes quite large. I think what @justinmoon meant was saving all possible invited codes, such that a different one can be tried in tests.

Unrelated to this issue I think it would be nice to allow an arbitrary number of urls to be encoded, such that a trade-off between invite code size and reliability can be found. f+1 URLs (2 in case of a 3-of-4 federation were f=1) are probably optimal, since if more than f guardians are down joining doesn't make sense anyway.

**Comment by kernelkind** [comment]
> @kernelkind this would make the invite codes quite large. I think what @justinmoon meant was saving all possible invited codes, such that a different one can be tried in tests.

I see now that having all the guardian urls in the `InviteCode` would be unnecessary, and that the purpose of this issue is to be able to use a different invite code in certain tests.

We can save all of the invite codes by copying the `invite-code` file in each data directory to `cfg_dir/invite-code-X` where X is the index of the guardian, with the exception of the 0th index, which should remain as `invite-code` to maintain backwards compatibility. Then a new method `Federation::invite_code_for(&self, peerId: u16) -> Result<String>` will grab the invite code for the federation at the specified peer id.

> Unrelated to this issue I think it would be nice to allow an arbitrary number of urls to be encoded, such that a trade-off between invite code size and reliability can be found. f+1 URLs (2 in case of a 3-of-4 federation were f=1) are probably optimal, since if more than f guardians are down joining doesn't make sense anyway.

I like this idea, I'd like to work on this after completing this issue.

**Comment by justinmoon** [comment]
@kernelkind Thanks for the detailed writeup!

Eric is correct -- I was just looking for a way of improving our test environment without changing any fundamental behavior.

But improving the fundamental behavior could also be very useful. Made issue here https://github.com/fedimint/fedimint/issues/4306

> We can save all of the invite codes by copying the invite-code file in each data directory to cfg_dir/invite-code-X where X is the index of the guardian, with the exception of the 0th index, which should remain as invite-code to maintain backwards compatibility. Then a new method Federation::invite_code_for(&self, peerId: u16) -> Result<String> will grab the invite code for the federation at the specified peer id.

This sounds good.
