### ISSUE TITLE
Add network to fedimint invite code

### ISSUE THREAD

**Issue by benthecarman** [fedimint/fedimint#4397]
It is non-obvious how to check for the network when joining a federation. The current way requires creating a wallet client and asking what the network is after you've connected to the federation. Would be nice if you check up font without needing to connect.

I imagine this was never done because the network is really at the module level rather than the federation level but would be nice to be able to have some indication.

**Comment by elsirion** [comment]
There is `FederationInfo`, which can be [constructed using an invite code](https://docs.rs/fedimint-client/latest/fedimint_client/struct.FederationInfo.html#method.from_invite_code) and contains the federation's config. You have to construct it anyway to build a client.

When it comes to the Bitcoin network: there has always been the tension how tightly to couple Fedimint to Bitcoin. In principle you could use it to build an independent transaction system, so we try not to assume anything about Bitcoin on the global level, it's delegated to modules. The two modules that are aware of their network/currency are the wallet and the LN module. [You find it in their respective configs](https://docs.rs/fedimint-ln-common/latest/fedimint_ln_common/config/struct.LightningClientConfig.html#structfield.network).

Since you probably don't want to talk to Federations without these modules anyway you can just require them to be present and read from their config.

**Comment by elsirion** [comment]
Note that the `FederationInfo` functionality might be merged with `ClientConfig` soon: https://github.com/fedimint/fedimint/pull/4297

**Comment by elsirion** [comment]
Actually, reviewing #4326 this morning I noticed that `ClientBuilder` doesn't require `FederationInfo` anymore, but takes `ClientConfig` directly again. We should really get #4297 merged then, I didn't know that API has such bad usability.

**Comment by justinmoon** [comment]
https://github.com/fedimint/fedimint/pull/4297 is merged
