### ISSUE TITLE
Gateway should detect internal payments

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#461]
Currently the Lightning Gateway doesn't recognize when it's paying itself. Unfortunately core-lightning doesn't seem to support self-payments. Thus we should detect these self-payments internally and special-case them (just buy the preimage directly instead of going through CLN).

**Comment by okjodom** [comment]
I'm rebuilding context on this issue after two days. As I recall, we discussed two possible solutions where:
1. We try avoid self pay within the gateway itself, OR
2. From client side, we avoid creating a contract where a gateway end up needing to pay itself [preferred]
 
On my first attempt to tackle approach number 2 above, inferring internal payments from the routing hint is turning out to be hard, and I suspect it's because the routing hint as we have now may not be sufficient information.

Here is my first attempt at adding user client logic to infer internal payments from routing hint:
```rs
    /// Infer if the invoice presented is an internal payment within the mint
    ///
    /// We do this by checking if the last hop for the invoice is to a gateway that is registerd with the mint
    async fn infer_internal_payment(&self, invoice: Invoice) -> Result<bool> {
        // Check if this invoice is to be routed through any of the gateways as a final hop
        if let Some(route) = invoice.private_routes().last().take() {
            match (**route).0.last().take() {
                Some(last_hop) => {
                    // Check if the last hop for this invoice is a gateway registered with the mint
                    match self.fetch_registered_gateways().await {
                        Ok(gateways) => {
                            for gateway in gateways {
                                if gateway.node_pub_key == (*last_hop).src_node_id {
                                    return Ok(true);
                                }
                            }
                            Ok(false)
                        }
                        Err(_) => Ok(false),
                    }
                }
                None => Ok(false),
            }
        } else {
            Ok(false)
        }
    }

    // Application

    pub async fn fund_outgoing_ln_contract<R: RngCore + CryptoRng>(
        &self,
        invoice: Invoice,
        mut rng: R,
    ) -> Result<(ContractId, OutPoint)> {
        if self.infer_internal_payment(invoice.clone()).await? {
            // TODO: Instead of creating an outgoing contract to be executed by a gateway,
            // should we create an internal contract to be executed by the mint?
            unimplemented!("Direct settlement of internal payment not implemented yet");
        }
        // ... elided
    }

```

Q: Do we have any additional hints within a user client for detecting internal payments?
Q: Should the inference for an internal payment be done on attempt to fund an invoice and create an outgoing contract? Looks like this is the right place but I'm confirming
Q: What should we do to settle internal payments without delegating to the gateway?
