### ISSUE TITLE
Investigate `No modules found of kind dummy` CI

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5286]
review club: dpc relayed that the problem was resolved by removing the diff that caused it. We should followup with an investigation to see what we were getting the `No modules found of kind dummy` error for the mint tests.

_Originally posted by @bradleystachurski in https://github.com/fedimint/fedimint/issues/5264#issuecomment-2110640119_

**Comment by dpc** [comment]
"what we were getting"?

I'm kind of confused, but assuming this means "why"...

The test is very artificial and hacked together from different pieces. Client and federation have only one module.

The refactoring made is so federation is still down (all peers have API not started), while the test starts already executing.

In the test the Client is new, but it doesn't do a normal initialization, and gets config passed to it. So the first thing that actually runs in the initial API version discovery. That API version discovery fails, because connections to all peers fail. So it does what it seems reasonable - returns that it's unable to find version to use for all modules.

A big WARN logs are printed "Unable to discover blabhablah", "Disabling module dummy", etc. so it was immediately clear (to me) what is going on, but it does need to be immediately clear to everyone.

The test moves on, tries to get client dummy module to print some fake money, and panics because the module is not there.

The root cause is the APIs are down. Normally this would lead to client failing to get a config, but the test is hacked to skip this part. So version discovery fails loudly but doesn't really panic.
