### ISSUE TITLE
Save incoming contracts to database

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#544]
In the process of facilitating an incoming lighting transaction, the lightning gateway [creates an "incoming contract" in the federation](https://github.com/fedimint/fedimint/blob/a34816e39bc7aa18d707786d08daea47a0e9e9f8/client/client-lib/src/lib.rs#L781-#L793).

We should [save this contract to the database](https://github.com/fedimint/fedimint/blob/a34816e39bc7aa18d707786d08daea47a0e9e9f8/client/client-lib/src/lib.rs#L800).

**Comment by justinmoon** [comment]
I think this one will probably just get implemented in the new client

**Comment by humansinstitute** [comment]
Hey - did this get picked up in the new lightning client rewrite or still outstanding?

**Comment by okjodom** [comment]
Ah yes. `IncomingStateMachine` [saves state in db](https://github.com/fedimint/fedimint/blob/ee8c6db636bbf9821716feb5fd1a1deac3a51072/modules/fedimint-ln-common/src/incoming.rs#L131C1-L133C15) if we successfully bought preimage from federation. This covers the gap we had in the old client, so this issue is resolved
