### ISSUE TITLE
Swap out a guardian's DNS

### ISSUE THREAD

**Issue by TonyGiorgio** [fedimint/fedimint#5482]
Without the ability to swap out a guardian's DNS, all federations are dependent upon DNS registrars. I have already seen a guardian's domain be unrightfully taken down and there's not a lot of ways to rectify this.

IMO, this completely changes the security model of Fedimint. No longer is protecting servers/keys a prerequisite. You now have to "protect" something you can not actually own.

If configs are hashed and federation IDs depend on the DNS the guardian set up in the beginning, then in its current form, there's no way to change these parameters without it looking like a completely new federation. Effectively nullifying all user funds.

The much needed ability to swap out Guardians would fix this, but are there any other short term fixes that can be put in place so that more federations don't have to shut down as a result?

**Comment by Kodylow** [comment]
Posting a summary of this issue and where it stands from the dev call this morning: current state, short term fixes/plans, and longer term removal of DNS as a dependency for guardian setup and transport layer. 

### BLUF
@joschisan or @elsirion will have more on this after speccing out the next development steps to get these into hotfixes and production. Short summary is: the fedimint threshold is working, there are options both short term and long term for removing the DNS dependency, we're confirming with everybody that the approaches discussed over the past few days are sound and speccing out development work to prioritize getting them out.

The current issue that prompted this is 2 federations each with a guardian using a .xyz domain had that domain put on automated server hold since a blacklist service flagged them, which apparently happens more with that .xyz registry specifically than other domains. 

#### Current State:
Both affected federations have 3/4 guardian thresholds and continue to operate with their 3 guardians. If another guardian goes down before the DNS issues get resolved and removed from the .xyz blacklists (looks like it can take a few days sometimes?), the federation won't progress but all the funds will still be safe, the guardian servers will just be waiting until they can create a threshold with a third guardian coming back online or potentially deploying a hotfix upgrade, after which the alef consensus will continue where it left off in processing transactions.

#### Where is the current DNS dependency?:
The current reliance on DNS is in the federation config where the guardians commit to their nyms and endpoints, modules, federation pubkeys, ecash keysets, etc. 

They also commit to an additional "meta" data section which, for the same reasons as this DNS issue, previously couldn't be changed since it had been set in the config. After hearing issues guardians had with not being able to change their metadata, we made a meta-module that allows the guardians to vote through the UI on key-value meta updates. Fedimint clients consume the initial client config from the guardians, confirm its hash matches the federationId from their inviteCode, then ask the guardians for updated revisions of the meta sections. This worked pretty straightforwardly with meta because it didn't require modifications to the initial config or the resulting federationId, and the metadata just needs to be signed by guardians as the most up to date revision.

Taking the above approach wouldn't work straightforwardly with the guardian endpoints. Modifying any of the guardians' endpoints in that initial client config would change the resulting hash and federationId, both assumed to be constant in the current client implementation. An invite code for a fedimint consists of a guardian's (or guardians') endpoints + a hash of the federation config. The client then uses the config as its reference for communicating with the other guardians, so modifying the DNS endpoint for any of the guardians is currently unsupported. Naively using the meta module's update mechanism would have issues as well like replaying old configs with compromised DNSes, etc.

#### Short Term Mitigations / Options:
After the call today, several devs are investigating between a couple short term options to rotate a guardian's endpoint without tearing down the federation and have it successfully consumed by the client. From the call today this didn't seem possible without a coordinated upgrade among the guardians + a client upgrade, but afterward there were a couple alternative ideas for this that are getting confirmed.

There are a few different ways to approach this, we're just debating which one works best as a hotfix and confirming what sort of upgrades might be needed by the guardians and by clients before posting the next steps for it. Joscha or Eric will probably post an update with a tracking issue once they slap the table on the correct approach in the next day or so.

#### Long Term:
The intention is to remove the DNS dependency for guardian setup / communication, but still allow federation guardians to expose themselves to clients over DNS which they can change through a threshold vote. The closest work on this issue is leonardo's ongoing work to add tor support on both the client and the server, there's PRs open for both right now and they're getting very close. 

For the general case of removing the dependency and using something like IP + noise, Joscha and Eric have an approach they believe is sound but had planned a longer development timeline for it. In light of this issue that'll probably have more clarity and an associated timeline but it's a fundamental change to the transport layer of Fedimint so will require significant dev work.

Again, this is updating pretty rapidly, thanks for bringing this up as an issue and will keep tagging here as things get finalized (and probably create a more formal tracking issue once the dev plans are solid)

**Comment by aljazceru** [comment]
replacing dns with IP doesn't accomplish much. You don't own IPs, they can easily be taken from you. Making anything around communication, be it ip, dns or onion address unchangeable seems bound to cause issues. First two (dns and ip) can be easily lost/taken away and shouldn't be used as unchangeable identifier (or identifier at all)

**Comment by Kodylow** [comment]
Yup, direction is not to just replace the dependency with another but to leverage the threshold and allow more flexible updates for guardian configuration when one of them wants to rotate something and have that new configuration acknowledged by the consensus and reflected to new and existing clients. again how this'll be implemented short term / long term are getting ironed out and there'll be more details up in the repo soon.

**Comment by dannydeezy** [comment]
if you're looking for domain instruments that you can actually own, rotate, and even easily buy and sell, then there's a decent solution available, but you guys probably will not like it due to religious reasons

**Comment by elsirion** [comment]
I've been mostly offline for the last two weeks since I was attending BTC Prague and the e-cash hackday the week after, but we did discuss this topic in person. I'll outline the idea that @joschisan and I came up with:

1. Introduce a new federation ID that isn't dependent on API endpoints but rather commits to session signing keys (since they already exist and we can re-use them securely with tagged hashing) [^1]
2. Authenticate API endpoint announcements via these keys, i.e. each guardian signs their own API endpoint announcements (should include an ever-increasing nonce to prevent replays).
3. Guardians exchange these announcements and make them available via their API. As long as one API endpoint stays reachable the others can be updated as long as new API announcements can be communicated to the guardian with the online API.
4. Clients re-fetch API announcements regularly and restart in case an API changed (shouldn't happen often).

Independently of this we should look into alternative transport layers (e.g. Tor being nearly ready), but that's not the immediate solution. Making the config more dynamic will help us deal with a wide variety of problems, so this is what we should focus on imo. 

[^1]: We should have done that all along but assumed that domains would be good enough till the end of the year given that domain censorship has been rare with the OG TLDs. We did not consider different policies of newer TLDs.

**Comment by dpc** [comment]
@dannydeezy Yo Dizzy!

> if you're looking for domain instruments that you can actually own, rotate, and even easily buy and sell, then there's a decent solution available, but you guys probably will not like it due to religious reasons

I would actually be perfectly fine with adding support for shitcoin based ID solutions and let users use them or not according to their own beliefs, but the problem is they actually don't help us at all:

* They don't have any broad support in standard DNS/web infrastructure. Please correct me if I'm wrong, but I'm only aware of Brave Browser and NextDNS support which is a tiny fraction of the userbase.
* Fedimints don't need human-readable domains. The names can be public-keys, and they are never shown to the user. It only needs censorship resistant names. Systems like https://github.com/Nuhvi/pkarr work perfectly fine for us, and require not shitcoins. From UX perspective it's waaay better, because act of getting a domain does not require manual interaction with an external system.


As much as I'm sympathetic to e.g. Handshake, which seems like a fine design for what it dos, there's no escaping the fact that global namespace creating artificial scarcity is an obsolete design in a world where browsers and applications alike increasing trying to hide the naming details from the user. 

If DNS servers and browser could support self-sovereign naming schemes like Pkarr, we would need nothing else campers Because they don't, it's probably better to implement client side libnoise tunneling.
