### ISSUE TITLE
Upgrade tests for `gatewayd` fail vs master

### ISSUE THREAD

**Issue by bradleystachurski** [fedimint/fedimint#5863]
https://github.com/fedimint/fedimint/actions/runs/10394815688/job/28785468549

I haven't done any investigation, but this appears to be the last log prior to failing

```
2024-08-14T20:54:19.272451Z  WARN fm::core: Getting {} gateway info via gateway-cli info failed error=command: gateway-cli --rpcpassword=theresnosecondbest -a http://127.0.0.1:10661/v1 info attempts=11
thread 'tokio-runtime-worker' panicked at /run/github-runner/runner-02-cc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/current.rs:50:46:
```

https://github.com/fedimint/fedimint/actions/runs/10394815688/job/28785468549#step:6:1364

**Comment by m1sterc001guy** [comment]
Investigating a little further, I think this might be the culprit https://github.com/fedimint/fedimint/pull/5663/files#diff-603d3cdc5619150c24a716fb0a053d804eb730d280c278c278aa8616ab9951de

**Comment by Kodylow** [comment]
Note from call: broke backwards compatibility between gatewayd and cli-extension, which in theory we're not maintaining anyway because gateway operators should be running the same version. Devimint didn't assume that though. After that happened the parallel channel open broke upgrade tests again, @m1sterc001guy is on it
