### ISSUE TITLE
Slow guardian recovery / synchronization

### ISSUE THREAD

**Issue by fparisotto** [fedimint/fedimint#6030]
For a federation that is running for months, with approx. 100k  sessions. The recovery process of a node from scratch (empty database) is taking 16k session/day. The CPU and network are mostly idle during the process.
It would be good to have this process optimized to avoid a longer downtime.

**Comment by elsirion** [comment]
Idea from a call with DPC: to not mess with consensus too much, which doesn't lend itself to fetch parallelization right now, we could have a pre-fetching process. The API client has a cache already anyway, so we'd be fetching future sessions (up to some point) and pre-fill the cache with that and the consensus could just request sessions sequentially as it does now.

**Comment by dpc** [comment]
Since it is using a custom api logic, it would require custom cache, or switching to use common api call with cache just like in other calls.

But for starter, I think the whole thing is bottlenecked on an artificial 5 second sleep for every session, which I believe is probably OK to remove, which should lead to 20x - 50x speedup right there.

**Comment by joschisan** [comment]
@dpc I think I now the line you mean - feel free to remove it and ping me for review.

**Comment by dpc** [comment]
I'm adding a backport label to the PR, but we should be careful rolling it out, as it's not impossible it might have some weird interactions w.r.t long requests and stuff like that will not show up in tests. Running it first for a day on some low profile federation would be a good idea.

**Comment by dpc** [comment]
We can re-open if it ever looks too slow again.
