### ISSUE TITLE
WASM bindings for client library

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#61]
If we want to eventually build a mobile/web client for MiniMint having [WASM bindings](https://rustwasm.github.io/book/) would be super useful. For that there probably needs to be a different API client that uses a WASM runtime compatible HTTP client and a different database implementation that doesn't rely on file system access but e.g. local storage.

**Comment by justinmoon** [comment]
It seems that [reqwest has support for WASM](https://github.com/seanmonstar/reqwest/pull/630)

**Comment by jkitman** [comment]
Rather than swap out the database implementation and HTTP client you could just have clients implement a system interface that the WASM code calls for better security/performance.

For instance, in the browser you can use local storage but for a mobile app you'd want to use the underlying file system for persistence and the secure keystore for private keys.

**Comment by Maan2003** [comment]
Most of it is already possible. We have [`Database`](https://github.com/fedimint/minimint/blob/603e9d1259d8c3a9d71d305bd1c8d42ec3457e24/minimint-api/src/db/mod.rs#L37) and [`FederationApi`](https://github.com/fedimint/minimint/blob/603e9d1259d8c3a9d71d305bd1c8d42ec3457e24/mint-client/src/api.rs#L16) traits. We can provide the concrete impls [during initialization](https://github.com/fedimint/minimint/blob/603e9d1259d8c3a9d71d305bd1c8d42ec3457e24/mint-client/src/clients/user.rs#L47).

There will be a separate `mintclient-web` crate which relies on the presence of web browser and will provide the web database impl. `mintclient-web` will use `mintclient` as a library (`mintclient` needs to compile to wasm).
