### ISSUE TITLE
CI: reuse build step for containers

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#644]
Would this make sense @dpc? Currently it seems like we rebuild `fedimitd` for the container job? This might be a better long term fix for #643, do the heavy builds+CI operations on BuildJet and let the remainder run on GH actions fetching artifacts from cachix.

```mermaid
flowchart LR;
    nix-build[Nix Build]
    nix-container[Nix Container Build]
    nix-build --> nix-container
    subgraph Nix CI
    nix-clippy[Clippy]
    nix-doc[Doc]
    nix-clippy --> nix-doc
    nix-audit[Audit]
    nix-doc --> nix-audit
    nix-etc[etc.]
    nix-audit --> nix-etc
    end
    nix-build --> nix-clippy
```

**Comment by dpc** [comment]
I don't understand what exactly you're proposing, but there's room to change things for use

There are couple of issues at play here IIRC. Just a recal. There are jobs that run in parallel and each job can have multiple steps.


* steps in a job reuse their results
* steps within one job can't run in parallel, so adding any extra step into the already longest "job" delays everything
* separate jobs running in parallel can't share building cache so they redo some work

There's some advantage/disadvantage to any setup here (total time to completion vs total time (aka price paid)).

Ideally what I'd want is run everything nix on one box, but after building all dependencies just splitting off and run other steps in parallel, since tests take a while to run but they underutilize the buildjet cpus. But that's not possible to express in github without stuffing own parallel runner in there which will get complicated.

**Comment by elsirion** [comment]
> But that's not possible to express in github without stuffing own parallel runner in there which will get complicated.

Are you sure? I think we could branch out after a successful build step usingthe [`'workflow_run`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) trigger.

**Comment by dpc** [comment]
> Are you sure? I think we could branch out after a successful build step usingthe [`workflow_run`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) trigger.

IIUC this and other possible parallelism methods work only on `job` level. So you can wait for a `job` to start and use this or `needs` to start one or more other jobs. But new job means new vm/container that starts with a completely new state, so will have to download things from cachix again etc. This gets painfull in PR builds as PR builds can't upload their artifacts to cachix at all, so these new jobs can't even download results that were already built - they have to redo them again.

**Comment by elsirion** [comment]
> This gets painfull in PR builds as PR builds can't upload their artifacts to cachix at all

Oh, I wasn't aware of that, I thought we could use it to transfer the build outputs from stage to stage. Is there a way to fix this? Otherwise we can close the issue.

**Comment by dpc** [comment]
> Is there a way to fix this? Otherwise we can close the issue.

I don't know of any. Some networked storage mounted in could work, but seems involved and bring another set of problems.
