### ISSUE TITLE
Invoice without amounts

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#701]
Can we support sending to or generating lightning invoices without amounts?

**Comment by justinmoon** [comment]
How would paying them work? Wouldn't the gateway still need to prove how much it sent? And AFAIK that's not possible.

**Comment by elsirion** [comment]
As discussed last Thursday: sending also isn't viable rn, since we can't enforce how much the GW actually sends when we leave routing to it. To enable amountless payments it appears we need client side routing (similar to hosted channels) or we could switch to BOLT12 where we don't need amountless invoices due to offers (#559).
