### ISSUE TITLE
Improve mint-client-cli help message

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#711]
```
$ cargo run --bin mint-client-cli
USAGE:
    mint-client-cli <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    help            Print this message or the help of the given subcommand(s)
    version-hash    Print the latest git commit hash this bin. was build with
```

Help / usage page should include all commands and their descriptions and usage.

**Comment by justinmoon** [comment]
@wilfredallyn want to take this one?

**Comment by yojoe** [comment]
I think this was working some time ago and was broken by the refactoring in commit 8cd2f6a28ee009e8f610de38d07506b461d290ef. @NicolaLS 

See comment: https://github.com/fedimint/fedimint/commit/8cd2f6a28ee009e8f610de38d07506b461d290ef#r85511197

I think if `workdir` is required for only a subset of all subcommands, it should be specified via a required argument `min-client-cli <SUBCOMMAND> --workdir=<PATH>` instead of a positional argument (current implementation). Seems like `clap` allows to build relationships between subcommands and their required arguments.

**Comment by wilfredallyn** [comment]
Looks like dpc is so fast that I didn't even have time to respond!
