### ISSUE TITLE
Make client library threadsafe

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#80]
In #71 (and also during some hacking with @justinmoon) I rediscovered the hard way that I didn't think about parallelism when building the client since it was only ever used in CI tests. This needs to be addressed to build robust clients. One way to do so would be using transactions that will be introduced in a fix to #25. A short term fix are `Mutex`es as discussed in https://github.com/fedimint/minimint/issues/71#issuecomment-1111503035.

**Comment by elsirion** [comment]
Update: `Mutex<()>` is actually kinda silly, a `tokio::sync::Semaphore::new(1)` should suffice for our purposes (that's how `Mutex`es are implemented internally).

**Comment by NicolaLS** [comment]
@elsirion wanted to give this a go recently but now client lib can't depend on tokio anymore (@Maan2003), I thought about just putting a Mutex<()> lock attribute in the
``` 
pub struct Client<C> {
    context: Arc<OwnedClientContext<C>>,
}
```

and have methods just decide by themselves (with a comment explaining why) weather they want to lock it or not (if they don't want to lock it they still need to acquire it but can drop it immediately). 
So every method would decide if they want to acquire it but every method would need to wait for it.
This is kind of bad because 1. Mutex and 2. We have no guarantee that a method is deciding correctly but I couldn't think of anything else..

**Comment by Maan2003** [comment]
this was discussed on telegram, we reached the conclusion:

use `&mut self` in the method if it needs to restrict concurrency.

**Comment by NicolaLS** [comment]
> this was discussed on telegram, we reached the conclusion:
> 
> use `&mut self` in the method if it needs to restrict concurrency.
> 
> The caller can put the Client in mutex if it needs to.

oh ok missed that thank you

**Comment by justinmoon** [comment]
Closing in favor of https://github.com/fedimint/fedimint/issues/1447
