### ISSUE TITLE
prevent liquidity attacks among competing ln-gateways

### ISSUE THREAD

**Issue by NicolaLS** [fedimint/fedimint#801]
LN-Gateways could setup an outgoing offer to a node that they control and let it expire making the other gateway lock-up funds in a htlc.
Because of the privacy of fedimint there is no way to know if it's a bunch of users or a single (malicious) gateway setting up many outgoing offers and let them expire to temporarily DoS the other gateway (depleting their outbound liq.). Also there is no cost of doing this and even if there was it could be offset with the expected fee they'll make on the other routings they "steal" from the other gws (making the profit less but still better than letting the other gw route).

Gateways could just not attempt payments with a long timeout which would make long-timeout invoices "more expensive" because after some amount the risk/reward will be enough for gws to attempt it. I don't know if this is a ok situation from an UX. POV.
Also following this game theory a gateway with a lot of funds would just keep the "outgoing contract mempool" full with offers (would just cost them the e-cash) to be the single gw to route long-expiry invoices.

I guess this could be revealed though if only one of lets say 5 gws is routing these kind of invoices and the others always pass on them.

**Comment by NicolaLS** [comment]
thinking about it even low time-out offers could be just spammed with no cost..
I don't know if I'm missing something but like this there will only be one highly funded gateway in a federation that can bully the others out.

**Comment by NicolaLS** [comment]
this would not be a problem if other gateways could just "sit it out" and wait for the monopol-gateway to get greedy and raise fees so they can jump as competition. but they wont ever be able to because their outbound can be lockes as long as the monopol-gatway has excess funds..and the monopol gw can demand whichever fees they want because they can distinguish the "real" user offers from their own fake ones

**Comment by jkitman** [comment]
The [channel jamming attack](https://bitcoinmagazine.com/technical/channel-jamming-bitcoin-lightning-network) is a general LN problem that hasn't been solved.

Fedimint LN introduces a new attack that doesn't even require committing liquidity.  An attacker could create Sybil users receiving over LN, forcing gateways to lock up ecash when they purchase the preimage offer which never gets paid.

Since we have a blinded mint there are some interesting solutions to Sybil attacks.  Obviously the most simple is for the federation or gateway to charge ecash fees, but that is a problem if the user doesn't yet have any bitcoin or ecash and needs to receive over LN.

We could issue blinded "reputation tokens" for users that can prove they are not a Sybil attacker when receiving over LN for the first time:
- Owning a certain amount of bitcoin UTXOs
- Has a unique Android or IOS root certificate
- Downloaded a unique copy of the client app
- Requests from a unique IP address

**Comment by justinmoon** [comment]
> An attacker could create Sybil users receiving over LN, forcing gateways to lock up ecash when they purchase the preimage offer which never gets paid.

This would only lock the gateway's funds for a few seconds, though, right? Because they only buy the preimage once the receive an incoming HTLC, and as soon as invalid preimage is observed they can reclaim their funds.

**Comment by jkitman** [comment]
> This would only lock the gateway's funds for a few seconds, though, right?

That's right, after looking at the code I realized the gateway can instantly refund.  The only lockup is the user funds can be locked up by a gateway.

> Definitely a problem, but not any more so than for any other lightning service, right?

Correct.  So I don't think we need any special DoS protection for LN outside of however we decide to handle DoS in general.  In fact we might be able to solve it in a way that LN nodes currently can't since we could have reputation tokens.

**Comment by NicolaLS** [comment]
consolidating this in #826
