### ISSUE TITLE
`UnwindSafe` is broken and might get removed

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#943]
BTW. the whole `UnwindSafe` is one of a few broken things in Rust and possibly will be deprecated altogether. https://github.com/rust-lang/rust/issues/40628

_Originally posted by @dpc in https://github.com/fedimint/fedimint/pull/941#discussion_r1027031397_

**Comment by dpc** [comment]
I don't think there's anything actionable here. If `UnwindSafe` gets deprecated it will just stop doing anything `AssertUnwindSafe` etc. will not be required anymore, so I just wanted to point out there's not much reason to worry about it.

We should generally avoid panicking, and if any task panicked `TaskGroup` should make so that the whole application shuts down right away anyway, with little time to do any damage due to broken invariants.
